### ISSUE TITLE
Issue with Installation Instructions

### ISSUE THREAD

**Issue by stingwraith** [mmabrouk/chatgpt-wrapper#1]
git clone https://github.com/mmabrouk/chatgpt-wrapper
Cloning into 'chatgpt-wrapper'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 18 (delta 4), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 5.24 KiB | 2.62 MiB/s, done.
Resolving deltas: 100% (4/4), done.
user@pc:~/Downloads/openai$ sudo pip install chatgpt-wrapper
[sudo] password for user:
ERROR: Could not find a version that satisfies the requirement chatgpt-wrapper (from versions: none)
ERROR: No matching distribution found for chatgpt-wrapper

**Comment by Natanel-Shitrit** [comment]
You should pass the folder as path, (`./chatgpt-wrapper`).
Without the `./` pip searches pypi for the package which doesn't exist.

**Comment by Natanel-Shitrit** [comment]
You can also use `pip install git+https://github.com/mmabrouk/chatgpt-wrapper`.
I PRed the changes so other people will not have this problem😄.

**Comment by mmabrouk** [comment]
thanks Natanel!

**Comment by EvanMath** [comment]
Hello,

I would like to add here an issue I had. While following the installation instructions I got the below error
![Στιγμιότυπο οθόνης_20221207_024626](https://user-images.githubusercontent.com/42109143/206183486-a7b2040a-2952-4d8b-8019-5b4a8abfffc7.png)

which was solved after changing line 4 in the `setup.py` file to 
```
with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()
```

**Comment by mmabrouk** [comment]
Thanks @EvanMath. I modified setup.py accordingly!
