### ISSUE TITLE
Is it possible to maintain context using the "quick response" method?

### ISSUE THREAD

**Issue by Daxiongmao87** [mmabrouk/chatgpt-wrapper#105]
I'm not sure if this is possible, but an option to maintain memory/context when using the 'quick response' method would allow quick contextual follow-ups without having to get into the chatgpt application.  I like to use chatgpt as a terminal side-kick and this would at least be valuable for my usecase.

**Comment by mmabrouk** [comment]
I really like the idea! I don't have much time to implement it currently, but I would welcome and help in any PR.

It should be fairly easy to do it, we just need to make sure to reuse the same session when using chatgpt from cli, and add some command like new when we want to start a new conversation

**Comment by thehunmonkgroup** [comment]
I'm not a fan of this idea, I really think conversation management should be handled at the level of the shell program.

That being said, you could certainly create a small wrapper around the Python module to accomplish this goal yourself.

**Comment by thehunmonkgroup** [comment]
I've considered this further, and I'm pretty sure there's not a clean way to implement it.

The main problem is accurately determining which conversation to associate a one-shot prompt to.

Even if we provided a config setting to enable it, the only sane setting would be 'most recent conversation', and without being inside the interface to have visibility on the conversation, it seems way too error prone (e.g. you forgot you started another conversation, then it uses that one, and now you have a message in the wrong conversation).

The only other option I can think of is passing a conversation ID with the prompt, but at that point, it really seems more efficient to just open the shell and navigate to the conversation.
