### ISSUE TITLE
Hiding conversations

### ISSUE THREAD

**Issue by nielstron** [mmabrouk/chatgpt-wrapper#106]
I automatically generate a high number of conversations. I would like to automatically hide a conversation after I am finished with it.

I am willing to implement this myself and had a glance at the playwright code but think I need some guidance on this :sweat_smile:

**Comment by mmabrouk** [comment]
That is a good idea. I would start by implementing 
`def remove_converstation(self, conversation_id:int)` in chatgpt.py.
For that, I would first look in the develper console what happens in network when you delete a conversation and try to emulate the call in the function. I looked quickly into it, it seems to be a PATCH http request.

**Comment by nielstron** [comment]
I saw that it is a PATCH request (using the uuid of the current conversation) but did not see how to submit requests with(in) Playwright.
