### ISSUE TITLE
Might be interested in using prompt_toolkit package

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [mmabrouk/chatgpt-wrapper#107]
Hi, thanks for this tool!

In case you don't know about [prompt_toolkit](https://pypi.org/project/prompt-toolkit/) it's a great prompt library quite easy to setup that could offer the following things : 
* vim like binding when typing
* multi line support (might be better than the current implementation, don't know)
* nicer autocomplete commands
* colors to differentiate the prompt from the answer

If you don't think it's relevant commentary feel free to close this. Have a nice day!

**Comment by mmabrouk** [comment]
Thanks for the suggestion. I would welcome a pr that improves over the current solution :)

**Comment by thiswillbeyourgithub** [comment]
I tried a bit of hacky stuff to overload the readline or input with prompt_toolkit and it was too unstable and confusing. It doesn't seem to be easy to use within cmd because it completely replaces both readline and cmd.

But after looking at  [the documentation](https://python-prompt-toolkit.readthedocs.io/en/master/) of prompt_toolkit I'm even more convinced that switching to their prompt instead of relying on readline+cmd could be a vast improvement and shorten / clarify the code :

* multiline support by default
* autocompletion
* keybindings
* vim or emacs binding
* colors
* syntax highlighting for many languages (could be useful for coding stuff)
* reverse and forward incremental history search
* multiplatform and pure python

I won't have time to do any PR unfortunately so I guess you probably won't be motivated to refactor all this but I wanted to write the cons of this at least :)

Have a nice day and feel free to close this.

**Comment by thehunmonkgroup** [comment]
For further clarification, prompt_toolkit can do a full-blown text user interface if you want to go that far. You could certainly implement a navigable history list, confirmation dialogs for destructive actions, and all kinds of fancy time-saving keyboard shortcuts.

Basically, this project would become a power user's dream ;)

That said, having implemented a TUI for Taskwarrior, I suspect it would be a fairly heavy lift.

**Comment by thiswillbeyourgithub** [comment]
(I think that increasing the complexity of chatgpt-wrapper in terms of prompt will be harder using cmd + readline than using prompt_toolkit as time goes on. Prompt_toolkit has lots of tools out of the box for this kind of situations IMO so the initial complexity would not be a heavy lift. But if the complexity increases, it will become either way even though I suspect it will be way harder with cmd+readline.)

**Comment by thehunmonkgroup** [comment]
As the maintainer of VIT (https://github.com/vit-project/vit), I can say with some confidence that making this a full TUI would probably be a heavy lift ;)

I get that libraries like Urwid/Prompt Toolkit do a lot, but the devil (and time sink) is always in the details.

That being said, to *just* convert away from `cmd/readline` with the most basic Prompt Toolkit implementation might not be too bad, after having poked around in the doc a bit.
