### ISSUE TITLE
`exit` command doesn't exit

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#108]
The instructions I've seen seem to indicate I can exit the running `chatgpt` wrapper by typing `exit` and hitting return.

However, that doesn't seem to be working for me:

```
$ chatgpt
Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> exit

Sure, feel free to type "exit" or "quit" to end the session. Let me know if you have any other questions before you go.

2> 
```

**Comment by mmabrouk** [comment]
the command is actually !exit and not exit. I will update the message
