### ISSUE TITLE
nice to have feature: managing ChatGPT errors

### ISSUE THREAD

**Issue by solyarisoftware** [mmabrouk/chatgpt-wrapper#11]
Nice project! Thanks

It is a very useful workaround, until the ChatGPT will be available (now is not, using standard openai API).

BTW, maybe it could be useful to catch connection / load errors as tese in screenshot:

![Cattura](https://user-images.githubusercontent.com/4106440/205956666-87b9c4c2-edc8-4d84-bf66-f129a09eaca1.PNG)

thanks again
Giorgio

**Comment by Tecuya** [comment]
https://github.com/mmabrouk/chatgpt-wrapper/pull/13

**Comment by mmabrouk** [comment]
@Tecuya solved this issue in his last PR (Thanks!). I will close this issue.
