### ISSUE TITLE
History list has 'New chat' as title for all chatgpt-wrapper conversations

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#110]
See here:

![2023-02-18_13-39](https://user-images.githubusercontent.com/43772/219884587-6dcd9fc8-a74c-40cb-87fe-806448a1ba29.png)

Wondering if there's a way to fix this, or if the API/implementation does not provide a mechanism.

**Comment by mmabrouk** [comment]
I noticed that, not sure what is the reason, I'd welcome a pr that fixes it

**Comment by mmabrouk** [comment]
Thanks for fixing this!
