### ISSUE TITLE
readline is not supported on Windows

### ISSUE THREAD

**Issue by vilimus** [mmabrouk/chatgpt-wrapper#12]
[readline](https://pypi.org/project/readline/) is used in the primary module, but is not supported on Windows, leading to installation problems. There is a Windows-supported alternative [pyreadline3](https://pypi.org/project/pyreadline3/).

**Comment by Tecuya** [comment]
https://github.com/mmabrouk/chatgpt-wrapper/pull/14 does this look right?  Can you confirm it fixes things on windows?

**Comment by vilimus** [comment]
I was able to get a working version on windows (https://github.com/vilimus/chatgpt-wrapper) but as @mmabrouk mentioned I have to *replace* the readline dependency with pyreadline3 (*not* pyreadline, which is outdated and throws errors).

**Comment by mmabrouk** [comment]
Thanks @vilimus 

What kind of error you get when using `readline`.  Does the error happen at the import line or much later?

Would the problem be solved by modifying the line:
```python
import readline
````
to 

```python
try:
  import readline
except:
  import pyreadline3 as readline
```

**Comment by vilimus** [comment]
@mmabrouk The error is
```sh
$ pip install readline
Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]
```
Here is a potential workaround using [environment markers](https://peps.python.org/pep-0508/#environment-markers):

In requirements.txt:
```
flask
playwright
pyreadline3; platform_system=="Windows"
readline; platform_system!="Windows"
rich
```

In the module:
```python
import platform
if platform.system() == "Windows":
  import pyreadline3 as readline
else:
  import readline
```
Here is some Stack exchange discussion about the platform module: [link](https://stackoverflow.com/questions/1854)

**Comment by Tecuya** [comment]
I went ahead and merged https://github.com/mmabrouk/chatgpt-wrapper/pull/14 with your recommended changes.  Hope it works!
