### ISSUE TITLE
Model version confusion

### ISSUE THREAD

**Issue by maxwellreuter** [mmabrouk/chatgpt-wrapper#120]
I noticed `text-davinci-002` appears in `chatgpt.py`:
https://github.com/mmabrouk/chatgpt-wrapper/blob/5b6714b481fa055745d1fc40b32190bbf9649bf4/chatgpt_wrapper/chatgpt.py#L127

Is this the model engine that this repo is communicating with? Or is it communicating with https://chat.openai.com/chat as I would interactively? If the latter is true, why is `text-davinci-002` in the code at all?

For some added context, OpenAI’s [“Model index for researchers”](https://platform.openai.com/docs/model-index-for-researchers) page says that `text-davinci-002` is “an InstructGPT model based on `code-davinci-002`.” It also lists `text-davinci-003` as “an improved version of `text-davinci-002`.”

I’m really confused about the versioning of GPT models: which version is the one known as “ChatGPT” to the public? If I’m querying `text-davinci-002`, can I say to my grandma that I’m querying ChatGPT? Or, would that be incorrect, because `text-davinci-003` is an updated version? Or are neither of these “ChatGPT?”

I also know there is a [waitlist signup](https://share.hsforms.com/1u4goaXwDRKC9-x9IvKno0A4sk30) opened by OpenAI for “ChatGPT API”, implying that it has no direct API at the moment.

I hope this post makes sense. Let me know if I can clarify anything.

**Comment by mmabrouk** [comment]
The model name in our case is the model name used in the endpoint that is called in the chatgpt webapp. To my understanding, this is a finetuned version of text-davinci-002 described in the version InstructGPT (https://github.com/openai/following-instructions-human-feedback/blob/main/model-card.md), but I am not sure to be honest.

**Comment by thehunmonkgroup** [comment]
I thought I could partially answer this question by inspecting the HTML on the main site, but it's a bit arcane:

![2023-02-23_17-50](https://user-images.githubusercontent.com/43772/221048641-bb3dcc5e-09cb-4a7c-ae49-164b9cfc3dcc.png)

I would have expected the model name to be in the name/id of an inspectable element, but it seems to be a layer or two down in the code. My guess is that `headlessui-listbox-option-:r3:` and `headlessui-listbox-option-:r4:` are the signifiers that get translated to the actual  model name.,,

**Comment by mmabrouk** [comment]
You can inspect the model name by looking in the network tab and checking the requests sent by chatgpt

**Comment by thehunmonkgroup** [comment]
I've got an even easier way from their site:

* Click 'New chat'
* Toggle the model selector (if you have one)
* You'll see the model string name in the URL

![2023-02-25_17-19](https://user-images.githubusercontent.com/43772/221382148-85df952d-4c33-4f9a-9817-5279ea0cb456.png)

The two models that their official site uses for 'Plus' users are:

 * Default: `text-davinci-002-render-sha`
 * Legacy: `text-davinci-002-render-paid`

In our code we also have the model for the free version:

```python
RENDER_MODELS = {
    "default": "text-davinci-002-render-sha",
    "legacy-paid": "text-davinci-002-render-paid",
    "legacy-free": "text-davinci-002-render"
}
```

IMO if you're using one of those you are doing the equivalent of what happens from their site.

**Comment by maxwellreuter** [comment]
I should have thought of this before, but when I make a query with your CLI, those queries will appear as "New chat"s on the left-hand-side of the official ChatGPT web interface.

**Comment by thehunmonkgroup** [comment]
@maxwellreuter really? We added code recently that auto generates a title just like the official website does, is that not working for you?

**Comment by maxwellreuter** [comment]
@thehunmonkgroup my bad, I didn't pull in a while. That feature is working for me.
