### ISSUE TITLE
commands not usable from a python script

### ISSUE THREAD

**Issue by douglasdnn** [mmabrouk/chatgpt-wrapper#121]
Commands like !read, !log, etc, are usable from the shell, but are sent as a normal chat input if sent from a python script.

**Comment by thehunmonkgroup** [comment]
Escaping the exclamation point might work, but if you're already in Python code, then I would recommend invoking the `ChatGPT` class directly, or doing the operation in Python as the shell class does -- the commands are specific to the shell class doing its job.
