### ISSUE TITLE
Chatgpt API

### ISSUE THREAD

**Issue by mmabrouk** [mmabrouk/chatgpt-wrapper#127]
It would be great to have an API interface for ChatGPT now that we can run it using Docker. This way, using ChatGPT in a project would be as simple as spawning a Docker image and interacting with the endpoints.

**Comment by thehunmonkgroup** [comment]
Check out #144 it seems to basically do the job.

**Comment by thehunmonkgroup** [comment]
This exists now, so closing. If we want any feature enhancements, let's file new issues for them.
