### ISSUE TITLE
Proposal: Change command leader from ! to something else

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#129]
The current 'leader' for commands is an exclamation point, e.g. `!help`

While it's clear that we need some kind of leader on commands, to distinguish a command from regular input, I think the exclamation point is a poor choice. Here's why:

1. The current architecture uses the `cmd` module, which already has a special treatment for a leading exclamation point, namely, it expects what follows to be a shell command, and even checks for a special callback in this case. From the module doc: `The command '!' is a synonym for 'shell', if a do_shell method exists.`
2. Entering an exclamation point requires hitting the shift key. Since the leader needs to be typed a lot, this slows down input unnecessarily. There are other quality leaders that do not need the shift key. For example, FreeSWITCH uses `/`, Sqlite uses `.`, even `;` would be a candidate.
3. Because of number 1 above, the implementation of tab completion is a lot worse, see #128 

While I understand that this would certainly be a breaking change, I believe it would be worth it if we expect this software to stick around awhile, and I would be willing to help with this refactor.

**Comment by mmabrouk** [comment]
I think that is a fair point. I think / would be a nice choice

**Comment by thehunmonkgroup** [comment]
Fixed, new leader is '/'
