### ISSUE TITLE
Commit access request

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#130]
Curious if you'd be open to granting me commit access on this project. I believe I've shown my skills and interest with the recent slew of PRs ;)

Been involved in open source a long time, here are a few of the projects I maintain:

https://github.com/vit-project/vit
https://github.com/thehunmonkgroup/luchia

And I've made significant contributions to these open source projects:

 - [FreeSWITCH](https://signalwire.com/freeswitch)
 - [Janus](https://janus.conf.meetecho.com/)
 - [Drupal](https://www.drupal.org/)

Would be happy to discuss further in real time as well. I've got a lot of momentum on this project, and it would reduce friction a lot for my continued contributions.

**Comment by mmabrouk** [comment]
Done :)

**Comment by mmabrouk** [comment]
I'd love to chat for 20 minutes though, my email is on my personal website (https://mahmoudmabrouk.com/)

**Comment by thehunmonkgroup** [comment]
Hm, the email link on your website isn't working, and I can't really make sense of the mailto: link, either!

**Comment by mmabrouk** [comment]
it's mahmoudmabrouk.mail@gmail.com
