### ISSUE TITLE
!history and set_title stopped working

### ISSUE THREAD

**Issue by Mahmoud-ModelMe** [mmabrouk/chatgpt-wrapper#132]
Both methods stopped working today, it could be a change in their internal api.
The previous implementation raised exception in the case set_title did not work, I modified it to logging a debug text. 
!history returned the following error. I just disabled the command for now. (unfortunately, I don't have much time the next couple of weeks, so the fixes here are badly written :/)

2> !history
INFO:root:Failed to get history: 403 Forbidden {'date': 'Wed, 22 Feb 2023 18:09:57 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '79d9ad00cba2ac9e-TXL', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
Traceback (most recent call last):
  File "/Users/mahmoudmabrouk/opt/anaconda3/bin/chatgpt", line 33, in <module>
    sys.exit(load_entry_point('chatGPT', 'console_scripts', 'chatgpt')())
  File "/Users/mahmoudmabrouk/code/chatgpt_wrapper/chatgpt_wrapper/main.py", line 79, in main
    shell.cmdloop()
  File "/Users/mahmoudmabrouk/opt/anaconda3/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/mahmoudmabrouk/opt/anaconda3/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/mahmoudmabrouk/code/chatgpt_wrapper/chatgpt_wrapper/gpt_shell.py", line 107, in do_history
    self._print_markdown("## Recent history:\n\n%s" % "\n".join(["1. %s: %s (%s)" % (datetime.datetime.strptime(h['create_time'], "%Y-%m-%dT%H:%M:%S.%f").strftime("%Y-%m-%d %H:%M"), h['title'], h['id']) for h in history['items']]))
TypeError: 'NoneType' object is not subscriptable

**Comment by thehunmonkgroup** [comment]
`!title` and `!history` are both working for me, just tested now.

The `403 Forbidden` in your error suggests that there's an issue with your session being authenticated.

**Comment by thehunmonkgroup** [comment]
If you've experienced this issue, it would be extremely helpful if you could offer more information to the developers about your setup, see the bottom of the original issue post at #142 for more info
