### ISSUE TITLE
How to prevent from outputing the warning of 'Failed to set title'?

### ISSUE THREAD

**Issue by ParadoxZW** [mmabrouk/chatgpt-wrapper#140]
For each ask, I get the output generated by ChatGPT with a warning like
```
2023-02-24 15:28:14,508 - WARNING - Failed to set title
```
It shows up before normal output when in Python and after when in Shell.

How to prevent this warning in those two scenarios?

**Comment by mmabrouk** [comment]
I fixed the issue. After reinstalling you should not get the warning anymore

**Comment by thehunmonkgroup** [comment]
If you've experienced this issue, it would be extremely helpful if you could offer more information to the developers about your setup, see the bottom of the original issue post at #142 for more info
