### ISSUE TITLE
Auto generation of title failing for some users

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#142]
#132, #133, #138, and #140 have all reported issues with failures to the `POST /backend-api/conversation/gen_title/[conversation_id]` endpoint that provides the convenience of having a reasonable title generated for a new conversation, instead of the completely unhelpful 'New chat'.

The challenge with these reports, and the attempted fixes:

- Not all users are experiencing this issue. I have not had it happen a single time
- Some users seem to be experiencing it constantly
- Users who are experiencing the issue do not want the program to crash, or to see constant warning messages logged
- Developers need input from users who are experiencing the issue in order to understand and fix the issue

I committed https://github.com/mmabrouk/chatgpt-wrapper/commit/19dcdbcc7ffebc81231da39404a315b9c3c99c4b just a bit ago, in a attempt to thread the needle on the various needs until the issue is better understood. As of this writing:

- The default `console` log level is now `ERROR`
- The log message about the title failing to set has been re-enabled, but set at level `WARNING`

This should hopefully work for everybody.

It would be *extremely* helpful if those of you who have experienced the issue can offer more details about your setup, including:

- Your location on planet earth (is this geo-location based)?
- Your server/computer environment (OS, etc.)
- Your network setup if it's unusual (running through a proxy, etc.)
- Anything else weird or non-standard you can think of about your setup

As I said, I have not experienced this issue a single time, and I use this app a *lot* -- there's just no way I've avoided it by random chance, something *has* to be something different about my setup than you folks who are experiencing the issue.

**Comment by mmabrouk** [comment]
It is indeed a weird issue, it happens sometimes but not all the time. It could be that openai did not roll out these features in all locations. Next time it happens to me, I will try tunneling through a US ip and test again.

Here is my data:
- Location: Germany
- Platform: MacOs
- Network: Straight forward

**Comment by thehunmonkgroup** [comment]
I think at this point, with the new logging and levels implemented, there's not much more we can do about this without more data from users experiencing the issue. I would suppose the best suggestions available at this time would be:

* Consider upgrading to a Plus account, which should reduce network load-type errors
* Try tunneling through an IP in another country (probably US)
* Wait and try again ;)

**Comment by thehunmonkgroup** [comment]
I've gotten no more recent reports about this, and believe it to be a temporary issue on OpenAI's end. Closing, feel free to reopen if the problem reappears.
