### ISSUE TITLE
fails to start after few successful uses

### ISSUE THREAD

**Issue by Seme4eg** [mmabrouk/chatgpt-wrapper#147]
logs output here: http://0x0.st/Hs04.txt
did 'chatgpt install', it opened firefox, logged in there, closed it, had couple successful usages, next day when tried to to use it again i always get this error log.

**Comment by mmabrouk** [comment]
make sure to kill all firefox instances and all instances of chatgpt_wrapper. remove the folder `rm -r /tmp/playwright` and restart

**Comment by Seme4eg** [comment]
aight, that did help
just so i know - that error has nothing to do that i use firefox as my main browser?
