### ISSUE TITLE
Prompt templates

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#148]
'Prompt engineering' seems to be all the rage with ChatGPT -- people providing instructions on formats to use, and even selling prompts: https://promptbase.com/

It seems true that there are certain repeatable formulas that users may employ, and it occurred to me that it might be nice to have the concepts of 'templates'.

There would be a few questions to answer before an implementation, such as:

* **Where would the templates live?** I could imagine a default XDG location of `$HOME/.local/share/chatgpt-wrapper/templates`, with the ability to override the location with a `--template-dir` argument
* **Would we want to support passing data to the template, and if so, how?** IMO this would only be necessary for the shell portion -- anybody using the `ChatGPT` class directly has many templating libraries available to do their work. One easy way to do it for the shell would be:
  * Use specially named tokens in the template that follow some kind of naming convention, like `###TOKEN_NAME###`
  * Parse the template and extract a list of unique tokens, then prompt the user for the value for each token replacement.
* **How would you invoke it?** Pretty easy: `!template [name]`, with `[name]` being the name of the file in the templates directory. `!template` without any argument would output a list of available template names. From there, we'd use the same mechanism as in the `!editor` command, but we'd pipe in the completed template as starting content.

None of this would be particularly hard, but it would be nice to get some feedback on the idea before I take a crack at it.

**Comment by mmabrouk** [comment]
I think that's a great idea. I had the same thought yesterday. Most of the time, I use ChatGPT with the same templates over and over again, such as 'solve this problem' and 'edit this text'.

Regarding the idea, I haven't given it much thought, but here are some initial considerations:

- Where should the templates be stored? We need to ensure that the parent directory is usable across all platforms. I came across this library yesterday that could be useful: https://github.com/platformdirs/platformdirs. Then we just need to make the subfolder we use hidden in Windows and start with a dot in MacOS and Linux.
- I think we should use a well-known templating format. Jinja is widely used and self-explanatory.
- Two interesting features of templates are taking inputs and combinability.
- These templates would require some inputs. We can limit these inputs to one in the beginning. For example, let's say I created a template to edit a PR message. The template could be something like `Please edit the following PR message to improve its quality and readability: {{message}}`.
  - The user could call the template using either `!t editprmsg sometext` (with a parameter) or `!t editprmsg` (without any parameter), which would open an editor window where they can paste the PR message (optionally this could be done on the shell just when using `!read`).
- Another interesting thing is combining templates. For example, I always use something like `Please keep your answer short and do not add any explanation`. This could be saved as a template named 'short' and be used together with another prompt. Although I'm not sure how we could deal with that. Maybe something like `!template [name1] [optional parameter] | [name2]`?. In our example that would be `!template editprmsg | short`

What do you think?

**Comment by thehunmonkgroup** [comment]
Using Jinja2 is an excellent idea!

In that case, wouldn't combining templates be a simple matter of using Jinja2's standard `include` syntax in the main template? I don't think we'd need to do anything in shell for that.

Also, (and thank you ChatGPT), Jinja2 provides a handy mechanism for extracting all the variable names from a template:

```python
from jinja2 import Environment, meta

def extract_variables(template):
    env = Environment()
    ast = env.parse(template)
    return meta.find_undeclared_variables(ast)

template = """
Hello {{ name }}!
{% for item in items %}
    {{ item }}
{% endfor %}
"""

print(extract_variables(template))
```

With this is would be trivial to read the template, then prompt the user for the values needed for the template.

I'm pretty agnostic on template storage, with the exception that I definitely believe we need both a default location, and a `--template-dir` override argument.

**Comment by mmabrouk** [comment]
I agree with everything you said

**Comment by thehunmonkgroup** [comment]
Done and done.
