### ISSUE TITLE
Vote up/down response

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#150]
The main webiste allows easily up/down voting a response.

I've envisioned a `!voteup` and `!votedown` command for this, which would apply to the most recent response.

I think it would be nice to have `>` alias to `!voteup` and `<` alias to `!votedown`.

**Comment by mmabrouk** [comment]
To be honest, I never use the thumbs up and down. I think we should be careful about adding too many commands to the project, as this may make it difficult for new users to use. Alternatively, we should ensure that the documentation is very clear about what is important and what is not.
As for using aliases that don't start with '!' (or '/' if we decide on that), I am personally against it. I believe it's too easy to accidentally upvote by copying and pasting some text that starts with '>', without actually intending to upvote.

**Comment by thehunmonkgroup** [comment]
Come to think of it, this is a feature probably best left to a full TUI implementation. It's certainly way down on the list.

**Comment by thehunmonkgroup** [comment]
Closing, as I think we want to keep the functionality to be generalized for possible introduction of other LLMs.
