### ISSUE TITLE
Mistyped commands shouldn't be sent to ChatGPT

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#152]
Anything starting with ! or whatever the command character might be in the future should be handled by the program itself. I can't count the times I've mistyped a command like !rfile for !file, and had that command sent to ChatGPT, and I have to wait for a response I know will be less than helpful. Anything starting with the command character that isn't a valid command or otherwise can't be interpreted as a valid command should result in an error message, rather than the invalid command being sent to ChatGPT.

**Comment by mmabrouk** [comment]
Good point. It would also be nice if we can find a way to stop generation from the cli.

**Comment by thehunmonkgroup** [comment]
#149 is filed for stopping responses. For this request, I think it's best to wait until we implement #107

**Comment by thehunmonkgroup** [comment]
Fixed.
