### ISSUE TITLE
Is there a way to use this in an asyncio loop?

### ISSUE THREAD

**Issue by infermi** [mmabrouk/chatgpt-wrapper#157]
I am trying to use the gpt wrapper using 
from chatgpt_wrapper import ChatGPT
but i get :
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
How do i fix it?

**Comment by mmabrouk** [comment]
We have a pending PR about this (#122), you can pull the PR code and test it

**Comment by infermi** [comment]
im sorry, im kinda new to github, how to i import the library as is with the asyncioChatGPT adition? i tried just changing the files in my python folder but i get many problems.
