### ISSUE TITLE
Differentiate the text between human input and chatGPT's response using font formatting

### ISSUE THREAD

**Issue by bboysnick5** [mmabrouk/chatgpt-wrapper#162]
Can we differentiate the text between human input and chatGPT's response using font formatting? Say human input usually question bold and chatGPT as it is now. 

Or even more fancier, notebook like with blocks to provide even further visual indication and layout.

**Comment by thehunmonkgroup** [comment]
I've added simple color coding to the role labels for the `/chat` command, and made the user prompt bold.

Unfortunately, there does not seem to be a reliable way to make the user input bold as they type.

I think these improvements are enough to solve the main issue, though.
