### ISSUE TITLE
Unneccessary `readline` dependency? 

### ISSUE THREAD

**Issue by SuperKenVery** [mmabrouk/chatgpt-wrapper#163]
This seems to be a built-in module in python. 

What's more, `pip install readline` fails on arm64 linux.

**Comment by thehunmonkgroup** [comment]
This will be solved and cleaned up when #107 lands.

**Comment by M3cubo** [comment]
I removed the dependency of readline, and the the installation worked: https://github.com/mmabrouk/chatgpt-wrapper/issues/158
