### ISSUE TITLE
About the differences and connections between `chatgpt-wrapper` and  `ChatGPT` python packages.

### ISSUE THREAD

**Issue by hongyi-zhao** [mmabrouk/chatgpt-wrapper#164]
I noticed that there are two very similar software packages based on Python, which have similar functions:

https://github.com/mmabrouk/chatgpt-wrapper
https://github.com/acheong08/ChatGPT

Are there any hints/comments for the differences and connections between them?

See [here](https://github.com/emacs-openai/codegpt/issues/7#issuecomment-1445583080) for some related discussion.

Regards,
Zhao

**Comment by SuperKenVery** [comment]
It seems the main difference is that 
- We use a real browser
- They don't, just sending HTTP requests

Frankly I haven't tried that one, but I guess they might have difficulty passing the browser check. To pass the check it might require a lot of reverse engineering. What's your experience using it?

**Comment by hongyi-zhao** [comment]
> What's your experience using it?

It doesn't feel nearly as good as the experience in the browser. That's why I'm trying to find another way.

As for this project, when I run the following command, as described [here](https://github.com/mmabrouk/chatgpt-wrapper#installation):

`$ proxychains-ng-socks5-country-control chatgpt install`

I was stuck, as shown below:

![image](https://user-images.githubusercontent.com/11155854/221590199-f3395b11-9b1c-40c4-be76-923dbc1b425f.png)


N.B.: `proxychains-ng-socks5-country-control` is proxy wrapper which helps me to login OpenAI's website.

**Comment by SuperKenVery** [comment]
- I would prefer clash or clash for windows for proxy. A virtual network interface eliminates lots of trouble. 
- To workaround this you could try changing different proxy servers in the world

**Comment by hongyi-zhao** [comment]
- By saying `clash`, do you mean [this one](https://github.com/Dreamacro/clash)?
- Do you mean set the proxy in the browser opened by running the `chatgpt install` the command, as shown below:

![image](https://user-images.githubusercontent.com/11155854/221603289-208ed0fc-84e3-49ce-8e9f-6d8ba7fc3160.png)

**Comment by SuperKenVery** [comment]
> this should indicate that there is nothing wrong with my login method and the proxy setting itself, but that the official ChatGPT server is currently at capacity and unable to let me continue to log in.

Yes exactly. That's why I say `workaround`... You did nothing wrong, but this might help.

**Comment by hongyi-zhao** [comment]
> No. I mean changing a proxy server. `proxychains-ng-socks5-country-control ` can use different proxy servers, right? Try changing to another country or region.

In my scenario, the above [proxychains-ng](https://github.com/rofl0r/proxychains-ng) script is calling an aggregation proxy under the hood, which already involves multiple proxies using load balancing with HAProxy, so, there is needless for me to do the manual switch of these proxies here.

**Comment by hongyi-zhao** [comment]
> Yes exactly. That's why I say `workaround`... You did nothing wrong, but this might help.

By saying this, your implication is that the ChatGPT server is a cluster-based distributed service. It is possible for us to use different nodes of the cluster service by changing the source link address of the client. So as to obtain possible service resources.

**Comment by hongyi-zhao** [comment]
https://github.com/mmabrouk/chatgpt-wrapper/issues/164#issuecomment-1446439281
> $ proxychains-ng-socks5-country-control chatgpt install

At this point, I have successfully logged in using the above method, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/221718214-68d76093-6a9f-482c-9d5c-456d37233128.png)

However, when I tested it further, I got stuck in the following step without any response:

![image](https://user-images.githubusercontent.com/11155854/221718639-a401048d-a41c-4525-b5d8-d34b30523665.png)

**Comment by hongyi-zhao** [comment]
The following is my use experience of Chatgpt-Wrapper:

1. After idle for a period of time, it will lose response if I try to initiate a conversation again.
2.  The response speed is relatively slow, as mentioned [here](https://medium.com/geekculture/using-chatgpt-in-python-eeaed9847e72).

**Comment by hongyi-zhao** [comment]
https://github.com/mmabrouk/chatgpt-wrapper/issues/164#issuecomment-1446354309
> But if they really did a great job reverse engineering all those stuff, they should provide a much better experience than this one.
> 
> What's your experience using it?

According to my test and comparison systematically, it seems that [`ChatGPT`](https://github.com/acheong08/ChatGPT) really outperforms [`chatgpt-wrapper`](https://github.com/mmabrouk/chatgpt-wrapper) in all aspects.

**Comment by SuperKenVery** [comment]
> After idle for a period of time, it will lose response if I try to initiate a conversation again:

If your session has expired there will be an alert, so I guess it might be because you got `Too many requests in one hour`. But you can also try running `/session` to refresh your session. 

There will be a big change... I'm planning on a PR which adds a lot of error handling, among which will automatically refresh the session or even page if something goes wrong.

**Comment by thehunmonkgroup** [comment]
@hongyi-zhao I haven't used that other project, but reading the code, it looks like you must depend on its proxy server, whereas this project has no such dependency.

**Comment by hongyi-zhao** [comment]
@thehunmonkgroup The proxy server is used to bypass the country service limit policy of OpenAI ChatGPT. So, I can't figure out why you say that "whereas this project has no such dependency". More specifically, if the user can access the OpenAI ChatGPT service, he/she must first have a method to bypass this restriction. In other words, the use of proxy is not the need for the project itself, but because of the user's geographical restrictions.

**Comment by thehunmonkgroup** [comment]
@hongyi-zhao I was unaware the proxy served that purpose. It still looked to me like you were required to send your requests through the proxy, but I may be wrong about that.

**Comment by hongyi-zhao** [comment]
@thehunmonkgroup As described [here](https://github.com/acheong08/ChatGPT#--optional-configuration), the proxy is an optional configuration, which is used to resolve specific situations on the user's side:

![image](https://user-images.githubusercontent.com/11155854/222328455-25b03f22-28b2-4f9f-8f96-9b3366ee4d58.png)

**Comment by thehunmonkgroup** [comment]
It looks like it only uses a browser to capture the session cookie, then closes it and just hits the chat.openai.com endpoints directly? if so, and if that works, it's probably a lot more responsive.

What else do you like about the project compared to this one?

**Comment by hongyi-zhao** [comment]
> What else do you like about the project compared to this one?

1. Automatic reconnection after disconnection.
2. [v3-official-chat-api](https://github.com/acheong08/ChatGPT#v3-official-chat-api) suppoorts.
3. Flexible, convenient and diversified [login authentication support](https://github.com/acheong08/ChatGPT#authentication-method-choose-1).
4. Simple and efficient installation and configuration steps.

**Comment by hongyi-zhao** [comment]
> This is indeed impressive. I can't imagine we'd implement that w/o funding support.

The most fascinating feature of [`ChatGPT`](https://github.com/acheong08/ChatGPT) is that it relies on a private bypass server under the hood to work perfectly. See [here](https://github.com/acheong08/ChatGPT/discussions/979) for more details.

> I agree we could improve our documentation, although I personally found installation/configuration quite easy.

I think the biggest drawback of installation for this project is that it's time-consuming: some dependencies require a lot of files to download.

**Comment by thehunmonkgroup** [comment]
> As for the how we're calling the API, it's via a closed source Cloudflare bypass for ChatGPT I wrote about a week ago.

OK, so that goes directly to my original point about an external dependency, I just had the dependency wrong! That project forces you to rely on an external dependency, and this one does not. There are tradeoffs to each approach, but I think it's inaccurate to say their approach is 'better' -- it's faster (good), and there's a big portion of it that's out of your control (bad).

> I think the biggest drawback of installation for this project is that it's time-consuming: some dependencies require a lot of files to download.

I don't understand this: `pip install` takes care of all the dependencies, what am I missing?

**Comment by hongyi-zhao** [comment]
> I don't understand this: `pip install` takes care of all the dependencies, what am I missing?

I refer to the following steps during the first installation:

![image](https://user-images.githubusercontent.com/11155854/222599989-93d0b9a0-3e75-42ef-b658-28d6231e89cd.png)

**Comment by thehunmonkgroup** [comment]
> I am referring to the second step during the initial installation of this package

So you don't like that there's one extra command you have to run? How much time is 'time consuming'? I don't recall having to do anything but run those two commands and wait a few seconds.

**Comment by hongyi-zhao** [comment]
I'm under the impression that this step involves downloading hundreds of megabytes of relevant files and takes a few minutes.

**Comment by thehunmonkgroup** [comment]
Well it has to download the browser to use. I suppose length of time depends on connection speed. I do find it interesting that waiting a few minutes for one command that has to be run once would be considered a downside of this project worth mentioning.

**Comment by hongyi-zhao** [comment]
The connection speed can't be controlled from user side, instead, it's determined by so many factors: ISP promised bandwidth, PyPI server available bandwidth, internet proxy health and bandwidth (if used), and so on.

**Comment by thehunmonkgroup** [comment]
@hongyi-zhao BTW I believe you can save a lot of download size by specifying the browser for Playwright to install, e.g. `playwright install firefox`, which in my last run, was only about 75MB of data.

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out. IIRC, I really omitted the browser parameter when running `playwright install`, based on the instruction [here](https://medium.com/geekculture/using-chatgpt-in-python-eeaed9847e72), as shown below:

![image](https://user-images.githubusercontent.com/11155854/222934897-f05cea04-84b7-435d-bde7-a1444a0ffccf.png)

Another question: This tool currently use `Enter` trigger sending user's message, which makes it impossible to enter multiple lines of text to ask questions. How to solve this problem?
