### ISSUE TITLE
Error: gpt_api.py  Response is a coroutine object

### ISSUE THREAD

**Issue by WeiLi1201** [mmabrouk/chatgpt-wrapper#170]
After running gpt_api.py, an error occurred when calling the 'conversation' API, response is a coroutine object, it‘s async method bug? 

<img width="917" alt="return a coroutine" src="https://user-images.githubusercontent.com/16485482/221809963-552dd9e8-e96f-43ac-8a11-66b02d0d6d22.png">

**Comment by WeiLi1201** [comment]
client request code like this. 
`
data = "今天你吃饭了没? 晚饭吃什么"
res = requests.post("http://127.0.0.1:5000/conversations", data=data.encode("utf-8"))
print(res.text)
`

**Comment by mmabrouk** [comment]
Should be fixed in #172 
Please reinstall
