### ISSUE TITLE
Error implementing asyncio.run(bot.ask(---)) with Flask API

### ISSUE THREAD

**Issue by Jesusmruiz1** [mmabrouk/chatgpt-wrapper#173]
An error occurs when two consecutive calls are made to the chatgpt instance. The first call always works correctly, but not the second or consecutive ones
"Firefox is already running but is not responding. The old firefox porcess must be closed to open a new window."

**Comment by thehunmonkgroup** [comment]
Can you provide some example code please? I'm not completely understanding your issue.

**Comment by namanh0705** [comment]
I have same error when have multiple request

`shutil.copytree("/tmp/playwright", self.user_data_dir)`

`shutil.Error: [('/tmp/playwright/lock', '/tmp/06c62870-c894-4e7d-be3d-05756cee97c8/lock', "[Errno 2] No such file or directory: '/tmp/playwright/lock'")]`

**Comment by thehunmonkgroup** [comment]
Async functionality has been deprecated, guessing this is no longer an issue.
