### ISSUE TITLE
Python async error. with Traceback

### ISSUE THREAD

**Issue by Mrw33554432** [mmabrouk/chatgpt-wrapper#175]
Traceback (most recent call last):
  File "C:\Users\shaow\Desktop\speak chat - Copy\try.py", line 4, in <module>
    response = bot.ask("Hello, world!")
  File "C:\Users\shaow\anaconda3\envs\speak\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 451, in ask
    return asyncio.run(super().ask(message))
  File "C:\Users\shaow\anaconda3\envs\speak\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "C:\Users\shaow\anaconda3\envs\speak\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Users\shaow\anaconda3\envs\speak\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\shaow\anaconda3\envs\speak\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\shaow\anaconda3\envs\speak\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 411, in ask
    response = list([i async for i in self.ask_stream(message)])
TypeError: 'async for' requires an object with __aiter__ method, got generator

**Comment by Mrw33554432** [comment]
In fact I am somehow addicted to multithread as it has much less chances to trigger an error like async XD

**Comment by Mrw33554432** [comment]
This error occurs when you try to use a generator object in an async for loop, but generators do not have an __aiter__ method required by async for loops.

In Python, async for is used to iterate over asynchronous iterables, which are objects that implement an __aiter__ method that returns an asynchronous iterator. An asynchronous iterator is an object that implements an __anext__ method, which returns an awaitable that resolves to the next value of the iteration.

Generators, on the other hand, are synchronous iterators that implement an __iter__ method that returns an iterator. The __next__ method of the iterator returns the next value of the iteration.

To fix the error, you need to use an asynchronous iterable instead of a generator. You can create an asynchronous iterable by defining a class that implements the __aiter__ method and returns an asynchronous iterator from its __aiter__ method.

Alternatively, you can convert the generator to an asynchronous iterator using the asyncio.to_asyncio_iterator() function. This function takes a synchronous iterator and returns an asynchronous iterator that implements the __anext__ method required by async for loops.

**Comment by Mrw33554432** [comment]
After checking the code, I believe the self.ask_stream will only return None while we have this code piece under self.ask `response = list([i async for i in self.ask_stream(message)])`

**Comment by Mrw33554432** [comment]
Perhaps you should separate the async version from the original version…then changes on one won’t change the other…

**Comment by thehunmonkgroup** [comment]
That's been done already, update your install.
