### ISSUE TITLE
Firefox is already running, but is not responding

### ISSUE THREAD

**Issue by namanh0705** [mmabrouk/chatgpt-wrapper#179]
When i have multiple request in 1 time, It got an error

`shutil.copytree("/tmp/playwright", self.user_data_dir)`

`shutil.Error: [('/tmp/playwright/lock', '/tmp/06c62870-c894-4e7d-be3d-05756cee97c8/lock', "[Errno 2] No such file or directory: '/tmp/playwright/lock'")]`

Please give me solution, thanks

**Comment by n71154plus** [comment]
same too

**Comment by SuperKenVery** [comment]
It seems because the lock file was existent when `shutil` was listing files but was deleted when it is copying... What about adding try/catch to the shutil.copytree?

**Comment by thehunmonkgroup** [comment]
@SuperKenVery would you be up for making a PR for your suggested improvement?

**Comment by SuperKenVery** [comment]
Now I think my previous explanation was wrong. I encountered this now, with only one request, but the `lock` is a **broken symbolic link**...
```python3
shutil.Error: [('/tmp/playwright/lock', '/tmp/86133846-743e-4b2d-82fb-98231d5747fe/lock', "[Errno 2] No such file or directory: '/tmp/playwright/lock'")]
```
```shell
file lock
lock: broken symbolic link to 100.117.111.55:+13040
```

**Comment by thehunmonkgroup** [comment]
This was fixed in a previous commit.
