### ISSUE TITLE
Figure out how to bind a key press to stop generating a response

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#180]
I haven't been able to figure out how to hook it to a key press from either the native `signal` module, nor `prompt_toolkit`'s keybindings, nor via `asyncio`'s signal handling -- they all give different errors. But, I  *can* send a signal from the system and that's working perfectly. At this moment, a SIGUSR1 will stop generating in the middle of a stream and properly clean up the running stream in the browser. Here's the script I'm using to send the SIGUSR1, which should be trivial to hook to a keypress at the OS level:
````bash
#!/bin/bash

PROGNAME="chatgpt"

pid=$(pidof -x ${PROGNAME})
if [ -n "${pid}" ]; then
  kill -SIGUSR1 ${pid}
fi
````

**Comment by kostecky** [comment]
I have a solution for you that works, but you may want to implement it more elegantly. I quickly modified `gpt_shell.py` and augmented the default() function to include a signal handler within it:

```
 ...
    async def default(self, line, title=None, model_customizations={}):
        def int_handler(signum, frame):
            print('Signal handler called', signum)
            os.kill(os.getpid(), signal.SIGUSR1)

        signal.signal(signal.SIGINT, int_handler)
...
```

![Screenshot 2023-03-21 at 12 50 23 PM](https://user-images.githubusercontent.com/159611/226683499-dcfd0d65-5e40-44d1-8630-71f630c94006.png)

**Comment by thehunmonkgroup** [comment]
@kostecky excellent find, thanks!

I'm not sure why this works, and registering the signal handler when init'ing the shell does not. Perhaps it's necessary to register the signal within the command loop in order for it to be scoped correctly.

Sadly, this still doesn't work on Windoze. It does catch the signal, but ends up killing the entire process anyways.

Good progress, though! Committed the improvement at https://github.com/mmabrouk/chatgpt-wrapper/commit/ce7ba0e4c3e2c3e1960ffd1f8d65931dc9dd1c96

**Comment by thehunmonkgroup** [comment]
I didn't realize you could register a signal handler in the event loop itself.

That may be a good long-term solution.
