### ISSUE TITLE
chatgpt install | module 'signal' has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by Barakita** [mmabrouk/chatgpt-wrapper#182]
PS C:\...> chatgpt install
Install mode: Log in to ChatGPT in the browser that pops up, and click
through all the dialogs, etc. Once that is achieved, exit and restart
this program without the 'install' parameter.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
\local-packages\Python311\Scripts\chatgpt.exe\__main__.py", line 7, in <module>
\site-packages\chatgpt_wrapper\main.py", line 78, in main
    chatgpt = ChatGPT(headless=not (install_mode or args.debug), timeout=90, **extra_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\site-packages\chatgpt_wrapper\chatgpt.py", line 476, in __init__
    asyncio.run(super().create(headless, browser, timeout, proxy))
site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
\Lib\asyncio\tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
\site-packages\chatgpt_wrapper\chatgpt.py", line 44, in create
    self._setup_signal_handlers()
site-packages\chatgpt_wrapper\chatgpt.py", line 80, in _setup_sig
nal_handlers
    signal.signal(signal.SIGUSR1, self.terminate_stream)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGUSR1'

**Comment by thehunmonkgroup** [comment]
God I hate Windows...

Uninstall and reinstall, should work now.
