### ISSUE TITLE
`ChatGPT` Python class broken when used directly.

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#191]
Fallout from the async updates, CLI seems to be working perfectly, but that's because it's not using the sync wrapper class.

Given this simple script:

```python
from chatgpt_wrapper import ChatGPT

bot = ChatGPT()
bot.refresh_session()
```

I'm getting these errors:

```
Traceback (most recent call last):
  File "/home/hunmonk/Downloads/test.py", line 4, in <module>
    bot.refresh_session()
  File "/home/hunmonk/git/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 500, in refresh_session
    return asyncio.run(self.agpt.refresh_session())
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/hunmonk/git/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 136, in refresh_session
    await self.page.goto("https://chat.openai.com/api/auth/session")
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9162, in goto
    await self._impl_obj.goto(
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 494, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 70, in inner_send
    done, _ = await asyncio.wait(
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 382, in wait
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 382, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 621, in _ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
Exception ignored in: <function ChatGPT.__del__ at 0x7f6f823b7c70>
Traceback (most recent call last):
  File "/home/hunmonk/git/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 535, in __del__
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  File "/home/hunmonk/git/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 121, in cleanup
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 13440, in close
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 421, in close
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 417, in close
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 70, in inner_send
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 382, in wait
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 382, in <setcomp>
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
  File "/home/hunmonk/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 621, in _ensure_future
ValueError: The future belongs to a different loop than the one specified as the loop argument
```

It seems pretty clear there's now something wrong with the way the sync wrapper is calling the async class.

@SuperKenVery any ideas how to fix?

**Comment by TheTS-labs** [comment]
Hi, I have the same problem, but I have a solution that worked for me:
```python3
import asyncio
from chatgpt_wrapper import AsyncChatGPT

async def main():
    agpt = AsyncChatGPT()
    await agpt.create(False, "firefox", "default", 60, None, None)
    await agpt.refresh_session()
    response = await agpt.ask("Hello, world!")
    print(response)
    # Hello there! How can I assist you today?

asyncio.run(main())
```

But you will need to change [chatgpt_wrapper/__init__.py](https://github.com/mmabrouk/chatgpt-wrapper/blob/main/chatgpt_wrapper/__init__.py) to do this:
```python3
from .chatgpt import ChatGPT, AsyncChatGPT
```

I think this problem is caused by multiple uses of `asyncio.run`

**Comment by thehunmonkgroup** [comment]
Yes, the async class (which we're using for the CLI) is working just fine, so your example code above would work with the small change you suggested.

We should do this anyways, to allow people the option to use either the sync or async interface, so https://github.com/mmabrouk/chatgpt-wrapper/commit/1788f024e645c0ac05ab4df52fafbde0ce7500d6

This still leaves the sync class broken, I've been playing with different attempts to overcome the event loop bug, but no luck so far.

**Comment by TheTS-labs** [comment]
Hehe, glad I could help.

**Comment by Just1z** [comment]
Hello, check this, please. 
#193

**Comment by thehunmonkgroup** [comment]
#193 does eliminate the errors, but my test script is hanging, which is not happening with the async class.

If we can figure it out, I can merge that PR.

**Comment by thehunmonkgroup** [comment]
I've merged #193 -- it's possible the script hanging is particular to my local setup. Can y'all give a shot at using the `ChatGPT` class directly and let me know if the issues are resolved?

**Comment by TheTS-labs** [comment]
It really doesn't seem to work, but this change works for me:
```python3
# ...
class ChatGPT:

    def __init__(self, headless: bool = True, browser="firefox", model="default", timeout=60, debug_log=None, proxy: Optional[ProxySettings] = None):
        self.agpt = AsyncChatGPT()
        self.event_loop = asyncio.new_event_loop()
        self.async_run(self.agpt.create(headless, browser, model, timeout, debug_log, proxy))

    def __getattr__(self, __name: str):
        if hasattr(self.agpt, __name):
            return getattr(self.agpt, __name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{__name}'")

    def async_run(self, awaitable):
        return self.event_loop.run_until_complete(awaitable)
# ...
```

**Comment by SuperKenVery** [comment]
I believe we are already using code like this in a very recent commit. Are you sure you are using the latest version?

**Comment by TheTS-labs** [comment]
I could be wrong, here is the last commit and its [chatgpt_wrapper/chatgpt.py](https://github.com/mmabrouk/chatgpt-wrapper/blob/43340d23b05a6c2656fc1a064505375530972e92/chatgpt_wrapper/chatgpt.py)(488-501 lines):
```python3
class ChatGPT:

    def __init__(self, headless: bool = True, browser="firefox", model="default", timeout=60, debug_log=None, proxy: Optional[ProxySettings] = None):
        self.agpt = AsyncChatGPT()
        self.async_run(self.agpt.create(headless, browser, model, timeout, debug_log, proxy))

    def __getattr__(self, __name: str):
        if hasattr(self.agpt, __name):
            return getattr(self.agpt, __name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{__name}'")

    def async_run(self, awaitable):
        return asyncio.get_event_loop().run_until_complete(awaitable)
```

**Comment by SuperKenVery** [comment]
For me when using your code, it hangs when running `ask_stream`. The current code in the repo works fine for me when `ask_stream`. 

However, the current code in the repository hangs when cleaning up at `await self.play.stop()`. 


My environment:

```shell
$ uname -a
Darwin ken.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
$ python
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ] on darwin
```

**Comment by SuperKenVery** [comment]
> It really doesn't seem to work

Could you provide a test script that fails?

**Comment by TheTS-labs** [comment]
Sorry, I checked again and the code works without my changes, here is the code that happens to work:

```python3
from chatgpt_wrapper import ChatGPT

def main():
    bot = ChatGPT(True)
    response = bot.ask("Hello world!")
    print(response)

if __name__ == "__main__":
    main()
```

**Comment by SuperKenVery** [comment]
Oh~ Glad it works.

**Comment by thehunmonkgroup** [comment]
I'm wondering if this is happening for some people and not others because of versioning difference?

@Just1z @TheTS-labs @SuperKenVery would y'all mind providing:
* The version of the playwright package you have installed
* The brand/version of the browser the you're using with playwright

Here are mine.
```
pip freeze | grep playwright
playwright==1.31.1
```
```
Firefox: 109.0 (64-bit)
```

I got the browser version by starting the wrapper with the `--debug` flag and selecting `Help -> About`

If it's working for some versions and not others, we can try pinning playwright, etc.

**Comment by Just1z** [comment]
Python 3.11.2
playwright 1.31.0
Firefox: 109.0 (64-bit)

**Comment by TheTS-labs** [comment]
Python 3.10.9
playwright==1.31.1
pytest-playwright==0.3.1
Firefox: 109.0 (64-bit)

**Comment by SuperKenVery** [comment]
Python 3.11.0
playwright==1.30.0
Firefox: 108.0.2 (64-bit)

**Comment by SuperKenVery** [comment]
Python 3.10.8
playwright==1.30.0
Firefox 108.0.2 (64-bit)

**Comment by thehunmonkgroup** [comment]
Based upon who said it was working, and everyone's versions, I'm not detecting any pattern that would suggest a problem w/ a version.

https://playwright.dev/python/docs/api/class-playwright#playwright-stop *seems* to indicate that we should be calling `stop()`, but when I commented out  that line and watched the process list, everything was cleaning up fine.

Are we even sure we need it?

**Comment by SuperKenVery** [comment]
> everything was cleaning up fine.

What script were you testing? 

If the whole python program ends, it's normal that its subprocess gets cleaned up by the OS. 
What we want to do is when the `ChatGPT` instance ends its associating browser gets closed.

**Comment by thehunmonkgroup** [comment]
@SuperKenVery I think I found the issue, it seems to be in your sync  implementation to handle the cleanup in `__del__`. Consider this change to the class:

```diff
diff --git a/chatgpt_wrapper/chatgpt.py b/chatgpt_wrapper/chatgpt.py
index e2120ba..801a294 100644
--- a/chatgpt_wrapper/chatgpt.py
+++ b/chatgpt_wrapper/chatgpt.py
@@ -508,5 +509,5 @@ class ChatGPT:
     def get_history(self, limit=20, offset=0):
         return self.async_run(self.agpt.get_history(limit, offset))
 
-    def __del__(self):
+    def cleanup(self):
         self.async_run(self.agpt.cleanup())
```

When I run this script:

```python
from chatgpt_wrapper import ChatGPT
from chatgpt_wrapper.config import Config

def main():
    config = Config()
    config.set('browser.debug', True)
    config.set('debug.log.enabled', True)
    gpt = ChatGPT(config)
    response1 = gpt.ask("Say, bot1!")
    gpt.cleanup()  ### This is the change.
    print(response1)

main()
```

The sync version does NOT hang.

So it seems we need to rethink how to handle cleanup. Also, I noticed `AsyncChatGPT` does NOT call `cleanup()`, which seems wrong. Am I missing something?

**Comment by SuperKenVery** [comment]
> The sync version does NOT hang.

Well, but doing this would require the user to manually call `cleanup`, which is kinda like manual memory management in C/C++ and I don't like it, especially when we're already using python. 

> AsyncChatGPT does NOT call cleanup()

`__init__` and `__del__` can't be async, so the cleanup code was in the `cleanup` method of `AsyncChatGPT`. I think that's as far as I can think of...

To let python automatically manage this we would need to define `__aenter__` and `__aexit` and use the context manager: 
```python3
with xxx as a:
    pass
```
However probably the class would be created in another class' `__init__` and context manager doesn't work.

**Comment by thehunmonkgroup** [comment]
> Well, but doing this would require the user to manually call `cleanup`, which is kinda like manual memory management in C/C++ and I don't like it, especially when we're already using python.

Well I don't like it, either, but I don't have a better idea yet ;) And this is still better than the `ChatGPT` class being broken, which it currently is. Do you have a better solution than the one I found?



> `__init__` and `__del__` can't be async, so the cleanup code was in the `cleanup` method of `AsyncChatGPT`. I think that's as far as I can think of...

So in this case, you'd have to call `cleanup()` manually for the `AsyncChatGPT` class, right?  If that's the case, then the proposal to require that for the `ChatGPT` class makes even more sense, as it's consistent.

**Comment by SuperKenVery** [comment]
Yes, users of the async one needs to call cleanup. 

But I think this is async related. All async class have this problem, as far as I understand. I hope the sync version can be more pythonic…

We provide the sync interface so that users of it doesn’t need to care about anything special but just write normal python code, I think.

**Comment by SuperKenVery** [comment]
Ahh, previous comment was on your second part. 

About the first part, yeah, an ugly but working one is definitely better than a broken one.

**Comment by thehunmonkgroup** [comment]
@SuperKenVery have a look here: https://docs.python.org/3/reference/datamodel.html#object.__del__

Most importantly: _It is not guaranteed that `__del__()` methods are called for objects that still exist when the interpreter exits._

And I've read a bit elsewhere that relying on `__del__` is probably not a good idea for cleanup. So I'm pretty confident now this approach needs to die.

I only see two viable options:

1. My current proposal, instruct the user of `ChatGPT` and `AsyncChatGPT` to call `cleanup()` manually if they are going to be creating and destroying lots of those objects. From my testing, that should NOT be necessary if a script just instantiates either class once -- the cleanup will happen when the script exits. Given that playwright is a process that's not entirely under our control, it further seems reasonable to require users of the class to ensure it's managed properly.
2. Build a context manager class that handles creation/management of multiple `ChatGPT` and `AsyncChatGPT` classes, then it can manage the `cleanup()` calls. This seems like way overkill to me, creating a layer of abstraction that makes things harder to maintain and reason about. Besides, users can always build this context manager themselves if they want what it can provide.

As you can see, I'm leaning hard towards solution number 1, so if I don't hear back with a better one in the next 24 hours, I'm going to implement it and update the documentation accordingly.

**Comment by thehunmonkgroup** [comment]
I went ahead and killed `__del__()`, since we know it's gotta go.

We can discuss further how we'll ask the users to handle cleanup, or implement it ourselves, but for now, the sync wrapper is basically functioning again.
