### ISSUE TITLE
ChatGPT official API

### ISSUE THREAD

**Issue by mmabrouk** [mmabrouk/chatgpt-wrapper#195]
The chatGPT official API is out (https://openai.com/blog/introducing-chatgpt-and-whisper-apis) (https://platform.openai.com/docs/guides/chat).
We should think on whether / how to integrate it. Integrating it won't be straight forward, since it requires re-implementing all the features of the webbrowser version. The official api provides only one endpoint where you would send the list of all the previous messages

import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

**Comment by thehunmonkgroup** [comment]
This would indeed be a big change, and it would also require paying for the service.

There would certainly be some complexity involved in managing the message threads to preserve context, but I think that would be pretty achievable.

Finally, there's no guarantee that the current free version will remain, which would of course completely obviate the browser interface.

Probably the best course of action is to start developing the API class (in place of our current Flask implementation), which would be separate from the current `ChatGPT` class. I think we could make both the existing and new API class conform to an interface so the shell class could use both.

**Comment by thehunmonkgroup** [comment]
Hm, it looks like they're only providing and endpoint to get responses to a string of messages.

This means implementing a storage layer to get a lot of the current functionality we have.

**Comment by thehunmonkgroup** [comment]
Eas-o peas-o so far: https://github.com/mmabrouk/chatgpt-wrapper/blob/chat-api/chatgpt_wrapper/openai_api.py

They just committed the `ChatCompletion` interface a few hours ago, it's not in an official release yet,  so you'd need to check out https://github.com/openai/openai-python and `pip install -e .` in that checkout to use it.

**Comment by jevgenij-breachgg** [comment]
@thehunmonkgroup thank you for announcing :) I will leave with your tool, at least some time :) it is cheaper :)

**Comment by bitmammoth** [comment]
Careful this breaks TOS now.

**Comment by thehunmonkgroup** [comment]
Implemented.
