### ISSUE TITLE
Change flask API port to 5001

### ISSUE THREAD

**Issue by gyliu513** [mmabrouk/chatgpt-wrapper#199]
https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c 

Port 5000 already in use — MacOS Monterey issue, if I test on MacOS, I have to change the port manually, this is not convenient for some test, can we update the port to 5001 or some other numbers? Thanks

**Comment by thehunmonkgroup** [comment]
https://github.com/mmabrouk/chatgpt-wrapper/pull/201#issuecomment-1451291104
