### ISSUE TITLE
Async function cause ChatGPT() not working in multithread

### ISSUE THREAD

**Issue by Mrw33554432** [mmabrouk/chatgpt-wrapper#203]
Because my project needs a true concurrent and keeps adding/closing concurrent thread, ask() just keeps returning.
RuntimeError: There is no current event loop in thread 'Thread-5'.
Is there any old version do not use async functions?

**Comment by jevgenij-breachgg** [comment]
@Mrw33554432 
this one probably 
pip install --upgrade git+https://github.com/mmabrouk/chatgpt-wrapper@9a87bc3c623e4940dc8e784eceb7029a23ca1ce5

**Comment by SuperKenVery** [comment]
Note: python has GIL and multithreading doesn't give you more CPU time. It's basically the same as coroutine. If you want more CPU time then you need multiprocessing.

For I/O intensive tasks, coroutines actually can be considered the same as multithreading. 

If you post your real needs, maybe we could provide more help.

**Comment by gyliu513** [comment]
I have same issue

```
There is no current event loop in thread 'Thread-2'.
/Users/guangyaliu/go/src/github.com/gyliu513/chatgptbot/3.py:71: RuntimeWarning: coroutine 'AsyncChatGPT.create' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function ChatGPT.__del__ at 0x10e44cdc0>
Traceback (most recent call last):
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 539, in __del__
    self.async_run(self.agpt.cleanup())
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 501, in async_run
    return asyncio.get_event_loop().run_until_complete(awaitable)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-2'.
/Users/guangyaliu/go/src/github.com/gyliu513/chatgptbot/3.py:71: RuntimeWarning: coroutine 'AsyncChatGPT.cleanup' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by thehunmonkgroup** [comment]
Have y'all tried using the new `AsyncChatGPT` class instead? Not sure, but that might help.

**Comment by thehunmonkgroup** [comment]
Async support has been removed.
