### ISSUE TITLE
Your ChatGPT session is not usable.

### ISSUE THREAD

**Issue by salvagarciaju** [mmabrouk/chatgpt-wrapper#212]
I cannot reactivate chatgpt.

Your ChatGPT session is not usable.
* Run this program with the `install` parameter and log in to ChatGPT.
* If you think you are already logged in, try running the `session` command.

**Comment by salvagarciaju** [comment]
Whatever he does, he makes me wait an hour. Does it happen to anyone else?

**Comment by SuperKenVery** [comment]
That's something OpenAI does, and has nothing to do with this project. 

And this happens if you log in your account in two different region at the same time.

**Comment by thehunmonkgroup** [comment]
Closing, out of scope.
