### ISSUE TITLE
the equivalent of "/switch" in api and python lib doesn't exist

### ISSUE THREAD

**Issue by yuanjv** [mmabrouk/chatgpt-wrapper#216]
I sorry. I just want to switch to old conversations.

**Comment by thehunmonkgroup** [comment]
You should easily be able to do this by manipulating the `self.conversation_id` and `self.parent_message_id` properties.

But, a helper method would be a nice convenience, and I'd accept a PR for that.

**Comment by yuanjv** [comment]
thx
