### ISSUE TITLE
BEWARE: your OS is not officially supported by Playwright; downloading fallback build

### ISSUE THREAD

**Issue by OrionRandD** [mmabrouk/chatgpt-wrapper#220]
I have tried to install it on Debian, inside a venv, but I get these errors:

cd ~/.virtualenvs/bin $
./playwright install chromium
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Chromium 111.0.5563.19 (playwright build v1048) from
https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip
Error: connect ETIMEDOUT 
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 
  port: 443
}

:(

and,

./playwright install firefox

gives me the same error...

:(

**Comment by thehunmonkgroup** [comment]
The error message seems quite clear -- use another distribution.

**Comment by OrionRandD** [comment]
> The error message seems quite clear -- use another distribution.

It is working greatly in Debian now...
No need to change OS:

~ $ chatgpt hello

Hello! How can I assist you today?

-> me@cypher 22:19:34
~ $ which chatgpt
which chatgpt
/home/me/.virtualenvs/bin/chatgpt

**Comment by thehunmonkgroup** [comment]
Great to hear.
