### ISSUE TITLE
Change return type annotation for ask() method in python api

### ISSUE THREAD

**Issue by asorgejr** [mmabrouk/chatgpt-wrapper#223]
The return type annotation for the `ask` method does not reflect the breaking change. It is currently marked as returning `str`, but should be `Tuple[bool, str, str]`.

**Comment by thehunmonkgroup** [comment]
There's only a few type annotations for return values, and some of them are wrong. I'm just going to rip them all out for now, and later take a pass at better annotations when the code base is more stable.
