### ISSUE TITLE
Exception('Unable to get token encoding for model gpt-3.5-turbo: not enough values to unpack (expected 2, got 1)')

### ISSUE THREAD

**Issue by sunhr19** [mmabrouk/chatgpt-wrapper#225]
i use chatgpt-api and when i ask to the chatgpt i got this ERROR: Exception('Unable to get token encoding for model gpt-3.5-turbo: not enough values to unpack (expected 2, got 1)').

maxos 13.2.1 (22D68)，here is my config.yaml
```
#the values in this sample configuration are the default values.
# Configuration syntax is YAML, learn more at: https://yaml.org


##########################################################
# Backend settings.
##########################################################
# The backend the shell should use, one of: chatgpt-browser, chatgpt-api
backend: chatgpt-api
# The database connection string, in a format SQLAlchemy understands.
database: sqlite:////Users/sunhr19/.local/share/chatgpt-wrapper/profiles/default/storage.db

##########################################################
# Shell settings.
##########################################################
shell:
  # NOTE: This setting is only available on the following backends: chatgpt-api
  # ustomize the prompt prefix, the following token are available:
  #   $USER: Logged in username
  # - $MODEL: The LLM model name
  # - $NEWLINE: Insert a newline
  # - $TEMPERATURE: The current temperature
  # - $TOP_P: The current top_p
  # - $PRESENCE_PENALTY: The current presence penalty
  # - $FREQUENCY_PENALTY: The current frequency penalty
  # - $MAX_SUBMISSION_TOKENS: The maximum number of tokens in a submission
  # - $CURRENT_CONVERSATION_TOKENS: The token count of the current conversation
   prompt_prefix: ($TEMPERATURE/$TOP_P/$PRESENCE_PENALTY/$FREQUENCY_PENALTY/$MAX_SUBMISSION_TOKENS/$CURRENT_CONVERSATION_TOKENS)$NEWLINE$USER@$MODEL

##########################################################
# Browser settings.
##########################################################
browser:
  # Enable debug mode (shows browser window if true, headless if false)
  debug: false
  # The browser to use, one of: firefox, chromium, webkit
  provider: firefox


##########################################################
# Chat settings.
##########################################################
chat:
  # The model to use when communicating with the server.
  model: default
  # When using the OpenAI API backend, the defaults for these values can be
  # customized. See
  # https://platform.openai.com/docs/api-reference/chat for more information.
  model_customizations:
    temperature: 1
    top_p: 1
    presence_penalty: 0
    frequency_penalty: 0
    # See '/help model_max_submission_tokens' for more information.
    max_submission_tokens: 4000
    # Configure aliases to switch between system messages, key is alias, value is message.
    # See '/help model_system_message' for more information.
    system_message:
      programmer: "You are an expert programmer, who responds to questions with brief examples in code."
  # If true, responses will be streamed in real time (no markdown formatting).
  streaming: true
  # Chat logs.
  log:
    # Enable logging to a file.
    enabled: false
    # Full path to the log file.
    filepath: chatgpt.log


##########################################################
# Log settings.
##########################################################
log:
  # Console logging.
  console:
    # Message format.
    format: '%(name)s - %(levelname)s - %(message)s'
    # Message level (must be valid Python logging module level).
    level: ERROR


##########################################################
# Debug settings.
##########################################################
debug:
  # Debug logging.
  log:
    # Enable to log debug messages.
    enabled: false
    # Full path to the log file.
    filepath: //tmpchatgpt-debug.log
    # Message format.
    format: '%(name)s - %(asctime)s - %(levelname)s - %(message)s'
    # Message level (must be valid Python logging module level).
    level: DEBUGC

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sunhr19/opt/miniconda3/bin/chatgpt", line 8, in <module>
    sys.exit(main())
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/main.py", line 16, in main
    asyncio.run(async_main())
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/main.py", line 156, in async_main
    await shell.default(" ".join(args.params))
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/gpt_shell.py", line 764, in default
    async for chunk in self.backend.ask_stream(line, title=title, model_customizations=model_customizations):
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/openai/api.py", line 351, in ask_stream
    new_messages, messages = self._prepare_ask_request(prompt, system_message=system_message)
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/openai/api.py", line 332, in _prepare_ask_request
    tokens = self.num_tokens_from_messages(messages)
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/openai/api.py", line 71, in num_tokens_from_messages
    encoding = self.get_token_encoding()
  File "/Users/sunhr19/opt/miniconda3/lib/python3.8/site-packages/chatgpt_wrapper/openai/api.py", line 66, in get_token_encoding
    raise Exception(f"Unable to get token encoding for model {model}: {str(e)}")
Exception: Unable to get token encoding for model gpt-3.5-turbo: not enough values to unpack (expected 2, got 1)

**Comment by thehunmonkgroup** [comment]
Cannot reproduce. Are you using the most recent version of `tiktoken`? The errors seems to be in the return value from that module.

Also, I can't make any sense of that config file, please fix the formatting.

**Comment by sunhr19** [comment]
Sorry about that, I have fixed it.I checked my tiktoken version is
```
$pip list | grep tik
tiktoken                0.3.0
```
I think it is a recent version.
Thanks for your help QAQ.

**Comment by thehunmonkgroup** [comment]
Can you please uninstall and reinstall, it's possible recent bug fixes may help. Also I'd remove most of that config, you only need the settings you're overriding, most importantly the `backend` setting.

If those don't help, you're gonna have to start inserting `debug.console` statements to get an idea of what's going on.

**Comment by sunhr19** [comment]
thanks for your help ;)
