### ISSUE TITLE
Running bot.ask() results in ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by rohis06** [mmabrouk/chatgpt-wrapper#226]
Hi!

I'm trying to use chatgpt-wrapper with Flask; however, I notice that when the program hits the line where bot.ask() is executed, it results in a **ValueError: signal only works in main thread of the main interpreter**.

I tried using the latest version of this codebase by running the following pip command:
```pip install --upgrade git+https://github.com/mmabrouk/chatgpt-wrapper@9a87bc3c623e4940dc8e784eceb7029a23ca1ce5```

My code:
```python
from flask import Flask, jsonify
from flask_cors import CORS
from chatgpt_wrapper import ChatGPT

  
# Initializing flask app
app = Flask(__name__)
CORS(app)


# Route for seeing a data
@app.route('/data')
def get_time():

    bot = ChatGPT()
    prompt = "Write a story"
    success, response, message = bot.ask(prompt)

    if success:
        res = {'Story': response}
    else:
        res = {'Story': message}

    return jsonify(res)


# Running app
if __name__ == '__main__':
    app.run(port=5000, debug=False)
```

Could someone please help me resolve this issue? Is there something that I'm missing, if yes, could you please comment what needs to be updated?

**Comment by thehunmonkgroup** [comment]
It's basically what the error message says, check Google for clarification.

The signal handling code should probably live in the base shell class instead of the base backend class, anyways, which should solve your issue.
