### ISSUE TITLE
New chat title generation POST request hanging

### ISSUE THREAD

**Issue by He2hiwei** [mmabrouk/chatgpt-wrapper#231]
I encountered a problem when calling the chatgpt.ask() function. My question is successfully passed to the OpenAI website, and the dialogue content (i.e., the response from chatgpt to my question) is also generated correctly on the OpenAI platform. However, my local program is unable to retrieve the answer. During the 'await response' process, the following error occurs: playwright._impl._api_types.Error: Request context disposed. Can you help me understand and resolve this issue?

My test code:
```python
from chatgpt_wrapper import ChatGPT
from chatgpt_wrapper.config import Config

config = Config()
config.set('browser.debug', True)
config.set('chat.model', 'legacy-paid')

bot = ChatGPT(config)
success, response, message = bot.ask("Can you tell me a joke?")
if success:
    print(response)
else:
    raise RuntimeError(message)
```
```bash
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\chatgpt-test\test.py", line 9, in <module>
    success, response, message = bot.ask("Can you tell me a joke?")
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 518, in ask
    return self.async_run(self.agpt.ask(message, title=title))
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 494, in async_run        
    return asyncio.get_event_loop().run_until_complete(awaitable)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 468, in ask
    response = list([i async for i in self.ask_stream(message, title=title)])
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 468, in <listcomp>       
    response = list([i async for i in self.ask_stream(message, title=title)])
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 444, in ask_stream       
    await self._gen_title()
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 204, in _gen_title       
    ok, json, response = await self._api_post_request(url, data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 188, in _api_post_request
    response = await self.page.request.post(url, headers=headers, data=data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\async_api\_generated.py", line 18313, in post
    await self._impl_obj.post(
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_fetch.py", line 248, in post
    return await self.fetch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_fetch.py", line 285, in fetch
    return await self._inner_fetch(
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_fetch.py", line 372, in _inner_fetch
    response = await self._channel.send(
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Request context disposed.
```
The dialogue content (i.e., the response from chatgpt to my question) is also generated correctly on the OpenAI platform:
![image](https://user-images.githubusercontent.com/22130161/225784964-6cff6d52-df54-4d63-a852-2f001b87702a.png)

**Comment by thehunmonkgroup** [comment]
Looks to me like the POST request to auto-generate a title is not returning.

I cannot reproduce. Possibly a transient error, I'd try again later.

**Comment by He2hiwei** [comment]
This issue occurs not only in the way Python is used, but also in the Windows command prompt shell. When I enter interactive mode in the Windows command prompt by typing chatgpt and input "hello world", the shell successfully replies to me with "Hello! How can I assist you today?" However, the following error occurs：
```bash
Hello! How can I assist you today?Error('connect ETIMEDOUT 74.86.226.234:443\n=========================== logs ===========================\n→ POST https://chat.openai.com/backend-api/conversation/gen_title/76152bbc-77b5-4efb-b903-0b74a7cf8d3c\n  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0\n  accept: */*\n  accept-encoding: gzip,deflate,br\n  authorization: Bearer ....\n  content-type: application/json\n  content-length: 91\n  cookie: ....\n============================================================')
```

**Comment by thehunmonkgroup** [comment]
Cannot reproduce in my local Windows installation.

This is likely a networking/firewall issue on your end.

**Comment by cloudyskyy** [comment]
> Cannot reproduce in my local Windows installation.
> 
> This is likely a networking/firewall issue on your end.

I am also facing the same problem.

**Comment by thehunmonkgroup** [comment]
Unlikely I'll be able to help here. If a Windows Python person figures this out and submits a clean PR to fix any issue with the module, I would commit it.

**Comment by He2hiwei** [comment]
> 后来解决了吗

The issue has not been resolved yet. If you have any solutions or other ideas, please feel free to share and contribute

**Comment by cloudyskyy** [comment]
> > 后来解决了吗
> 
> The issue has not been resolved yet. If you have any solutions or other ideas, please feel free to share and contribute

Yes, kind of 'solved' ...
I found a strange phenomenon: When I rolled back the version to chatgpt 0.3.16, it suddenly stopped reporting this error, and the python API could return normal response of chatgpt. Once upgraded to chatgpt 0.3.17 or higher, the problem reappeared.

**Comment by cloudyskyy** [comment]
> Unlikely I'll be able to help here. If a Windows Python person figures this out and submits a clean PR to fix any issue with the module, I would commit it.

I found a strange phenomenon: When I rolled back the version to chatgpt 0.3.16, it suddenly stopped reporting this error, and the python API could return normal response of chatgpt. Once upgraded to chatgpt 0.3.17 or higher, the problem reappeared.

**Comment by cloudyskyy** [comment]
> > 后来解决了吗
> 
> The issue has not been resolved yet. If you have any solutions or other ideas, please feel free to share and contribute

`git checkout 5b6714b481fa055745d1fc40b32190bbf9649bf4`
`pip install -e .`
This is how I roll back to chatgpt 0.3.16.

**Comment by He2hiwei** [comment]
> > > 后来解决了吗
> > 
> > 
> > The issue has not been resolved yet. If you have any solutions or other ideas, please feel free to share and contribute
> 
> Yes, kind of 'solved' ... I found a strange phenomenon: When I rolled back the version to chatgpt 0.3.16, it suddenly stopped reporting this error, and the python API could return normal response of chatgpt. Once upgraded to chatgpt 0.3.17 or higher, the problem reappeared.

Thank you very much for sharing. I have tested your method on my computer and it works. Rolling back to version 0.3.16 enabled ChatGPT to could return normal response.

**Comment by thehunmonkgroup** [comment]
@He2hiwei @cloudyskyy are either of you able to test if, in the most recent release, you can set a title in the shell version of the wrapper?

I'm asking because that is essentially the same kind of `POST` request as the auto title generation, it might provide a clue, or at least an easy way to reproduce the issue.

To test, you can simply switch to your most recent chat in the shell, and try to set the title:

```
/switch 1
/title [some new title]
```

**Comment by cloudyskyy** [comment]
> @He2hiwei @cloudyskyy are either of you able to test if, in the most recent release, you can set a title in the shell version of the wrapper?
> 
> I'm asking because that is essentially the same kind of `POST` request as the auto title generation, it might provide a clue, or at least an easy way to reproduce the issue.
> 
> To test, you can simply switch to your most recent chat in the shell, and try to set the title:
> 
> ```
> /switch 1
> /title [some new title]
> ```

![image](https://user-images.githubusercontent.com/30574139/226803661-cd8d6b7d-205c-4f24-a23b-92981eaa8743.png)

I have a suspicion if this is the root of the problem?

Currently my **list of titles** is unavailable, so the POST request is hanging?

This issue of "no title list" happens possibly when I had too many conversations with chatgpt. I have used the wrapper for a month, and I often establish a new conversation. At some time the title list suddenly disappeared.

btw, I have a chatgpt-plus.

**Comment by thehunmonkgroup** [comment]
@He2hiwei @cloudyskyy can you please try the latest release and see if that fixes the issue for you?

I've added a sensible timeout for the auto title generation, and put in better error handling -- I think it will work fine in your cases.

**Comment by cloudyskyy** [comment]
> @He2hiwei @cloudyskyy can you please try the latest release and see if that fixes the issue for you?
> 
> I've added a sensible timeout for the auto title generation, and put in better error handling -- I think it will work fine in your cases.

IT WORKED !
Thank you very much for your help!

**Comment by thehunmonkgroup** [comment]
Great, assuming this issue is resolved.
