### ISSUE TITLE
How to set `echo' to false under the `chatgpt-api' backend?

### ISSUE THREAD

**Issue by chenzhawyang** [mmabrouk/chatgpt-wrapper#232]
Although according to https://platform.openai.com/docs/api-reference/completions/create, `echo` is set to false by default, but when I use the `chatgpt-api` backend my prompt is still being echoed back to me. Is there a way to modify this behavior?

**Comment by thehunmonkgroup** [comment]
We don't use that endpoint, we use https://platform.openai.com/docs/api-reference/chat/create

I see that also has an `echo` parameter, but we don't mess with that, so it will be using the default value.

So I'm not sure what you're experiencing. If you're in the shell, you will see the prompt as you type it.

**Comment by chenzhawyang** [comment]
thehunmonkgroup ***@***.***> writes:

> So I'm not sure what you're experiencing. If you're in the shell, you
> will see the prompt as you type it.

I am sorry, I found out that 

```
1> hello world!
hheelllloo  wwoorrlldd!!

Hello there! Is there anything you'd like to talk about or any questions
I can help you with?
```

This kind of behavior only occurs when I use `chatgpt` in emacs
(`comint`, `eshell`, &c.) I think this is rather an emacs thing. Thank
you for the clarification.
