### ISSUE TITLE
PluginManager - ERROR - Plugin awesome not found in search path. ModuleNotFoundError: No module named 'chatgpt_wrapper'

### ISSUE THREAD

**Issue by xuzhi2021** [mmabrouk/chatgpt-wrapper#239]
Thanks for the wonderful project. I have some installation problems. My OS: Win10. I followed the instructions. When I ran "chatgpt install" in cmd, it reported:
"
PluginManager - ERROR - Error loading plugin awesome from ...(correct path)\chatgpt_wrapper\plugins\awesome.py: 'gbk' codec can't decode byte 0x9d in position 7637: illegal multibyte sequence
PluginManager - ERROR - Plugin awesome not found in search path
"
When I ran in the terminal of pycharm, it just reported "PluginManager - ERROR - Plugin awesome not found in search path". But in these two ways, it both opened a browser. I logged in the chatgpt normally. Then I ran "chatgpt",  cmd still reported the same error as above. But I could ask chatgpt questions and it responsed normally.

I don't know how to solve this. I tried to encode awesome.py in gbk, but it didn't work. 
I guess this error leads to the failure of running python code

 `from chatgpt_wrapper import ChatGPT
bot = ChatGPT()
success, response, message = bot.ask("Hello, world!")`. 

The error message said "ModuleNotFoundError: No module named 'chatgpt_wrapper'".  Then I ran "pip install chatgpt_wrapper" and it reported "ERROR: Could not find a version that satisfies the requirement chatgpt_wrapper (from versions: none)
ERROR: No matching distribution found for chatgpt_wrapper" Can anyone help? Thanks a lot!

**Comment by thehunmonkgroup** [comment]
Fixed in latest release.

**Comment by xuzhi2021** [comment]
> 

Thanks for reply! But I know some others use Windows but didn't encounter this bug. Is it because they use previous release? (which maybe not use plugin awesome?)

**Comment by thehunmonkgroup** [comment]
OK, should now be fixed in https://github.com/mmabrouk/chatgpt-wrapper/commit/699c4bc7f65d55205cc802a76eb3e456340c0698

You may need to `/awesome reload` to reload the file with the updated encoding.

**Comment by robbintt** [comment]
```Awesome - ERROR - Error writing prompts file: binary mode doesn't take an encoding argument
PluginManager - ERROR - Error loading plugin awesome from /home/robbintt/virtualenvs/chatgpt_wrapper/lib/python3.10/site-packages/chatgpt_wrapper/plugins/awesome.py: [Errno 2] No such file or directory: '/tmp/awesome-prompts.csv'
PluginManager - ERROR - Plugin awesome not found in search path
```

I am having this issue on latest using ubuntu 22, haven't investigated yet, I reinstalled just now and have an additional error (above).


```
(chatgpt_wrapper) 🔥 cat requirements.txt 
# dependencies aren't explicit or pinned for now
chatGPT @ git+https://github.com/mmabrouk/chatgpt-wrapper@mai
(chatgpt_wrapper) 🔥 pip install -r requirements.txt                                                                          
Collecting chatGPT@ git+https://github.com/mmabrouk/chatgpt-wrapper@main                                                      
  Cloning https://github.com/mmabrouk/chatgpt-wrapper (to revision main) to /tmp/pip-install-2yuaevdk/chatgpt_32b017ffead94449
a94fc24a2338a5e1                                                                                                              
  Running command git clone --filter=blob:none --quiet https://github.com/mmabrouk/chatgpt-wrapper /tmp/pip-install-2yuaevdk/c
hatgpt_32b017ffead94449a94fc24a2338a5e1
  Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit 88b8e5bb91edadc67082e29c8f76f2ba0fb9ec54
   
...
...
 ```

**Comment by xuzhi2021** [comment]
> 

I retried and succeeded. Maybe you can try to clone the repository again and follow the instructions :
cd chatgpt-wrapper
pip install -e .
playwright install firefox
chatgpt install

**Comment by robbintt** [comment]
I have this problem on macos (separate install/platform) too. I haven't had
time to look into it yet:

```
Awesome - ERROR - Error writing prompts file: binary mode doesn't take an
encoding argument
PluginManager - ERROR - Error loading plugin awesome from
/Users/trobbins/virtualenvs/chatgpt_wrapper/lib/python3.8/site-packages/chatgpt_wrapper/plugins/awesome.py:
[Errno 2] No such file or directory:
'/var/folders/j2/yjrv008x4tzbrlz9136zq9900000gn/T/awesome-prompts.csv'
PluginManager - ERROR - Plugin awesome not found in search path
```

**Comment by thehunmonkgroup** [comment]
@robbintt should be fixed by https://github.com/mmabrouk/chatgpt-wrapper/commit/ed4b6b942a4dfdee86a1d7a11a29b2252b314f22

**Comment by robbintt** [comment]
Fixed, thanks!
