### ISSUE TITLE
script to launch chatgpt interactive mode with arguments passed in

### ISSUE THREAD

**Issue by luutuankiet** [mmabrouk/chatgpt-wrapper#244]
Hi, I have successfully installed chatgpt on my windows machine. As far as the documentation goes I understand that interactive mode does not accept arguments passed in at runtime (e.g. if I programmatically execute a sequence `chatgpt && /login username && hello world`). 
To achieve the above output I must first launch the single command `chatgpt` , then pass in succeeding commands. 
I am currently resort to one-off cli command `chatgpt %arg`.

Is there any way to go about this use case?

**Comment by thehunmonkgroup** [comment]
You can wrap the Python module with any shell functionality you want.

**Comment by luutuankiet** [comment]
sorry if my descriptions were unclear but I don't think your answer points to the issue  : is it possible to create a batch script that executes the following 3 separate steps into 1 ?
1. `chatgpt`
2. `/login username`
3. `hello world`

**Comment by thehunmonkgroup** [comment]
Yes, wrap the Python module in whatever functionality you want, the `ApiShell` class does this, you can take inspiration from there.
