### ISSUE TITLE
feature request: select template from cli flags, start new session if template specified

### ISSUE THREAD

**Issue by robbintt** [mmabrouk/chatgpt-wrapper#246]
not sure if there's an alternative way to accomplish this.

**Comment by thehunmonkgroup** [comment]
Not clear what you're wanting to accomplish here. Can you provide a specific use case and example usage?

**Comment by robbintt** [comment]
Sure, templates are generally a first message to set chatgpt for a
particular session. So this would send the template as an initial message
on launching the session.

**Comment by thehunmonkgroup** [comment]
I'm currently of the opinion that the `chatgpt` executable's purpose is to be an *interactive* shell, and I've become resistant to the idea of adding more arguments to it, especially in the one-shot case -- it seems reasonable to have an argument that sets a default or configuration-related variable, but anything to do with messages, I think you should:

* Use the interactive shell, or:
* Use the Python module for any kind of customization needed

It should be quite easy to use the Python module to implement whatever kind of feature you desire, and looking at how the shell does it can act as an excellent guide for that purpose.

**Comment by thehunmonkgroup** [comment]
Implemented in https://github.com/mmabrouk/chatgpt-wrapper/commit/19e195dc162e664fdf65d1c82f64a89d94a4ddf1
