### ISSUE TITLE
code-davinci-002 and other model inclusion?

### ISSUE THREAD

**Issue by kostecky** [mmabrouk/chatgpt-wrapper#250]
Hi there, is there a way to allow for code-davinci-002 to be used as a model in the gpt-shell? Am I missing something obvious where I can already do this?

What I get now is:

```
/model text-davinci-002
Invalid model, must be one of: default, turbo, turbo-0301, gpt4, gpt4-0314, gpt4-32k, gpt4-32k-0314
```

**Comment by thehunmonkgroup** [comment]
We only support the chat completions endpoint at this time.

Given that OpenAI seems to be moving away from the completions endpoint in favor of the chat completions endpoint, it's unlikely we'll add support for it.

Model compatibility for endpoints: https://platform.openai.com/docs/models/model-endpoint-compatibility
