### ISSUE TITLE
Might be good to standardize on langchain prompt yaml format

### ISSUE THREAD

**Issue by robbintt** [mmabrouk/chatgpt-wrapper#258]
I am evaluating langchain this weekend, and found their prompt format: https://python.langchain.com/en/latest/modules/prompts/examples/prompt_serialization.html

Short term I plan to integrate the chatgpt-wrapper playwright backend to langchain, ideally just using python.

Long term I expect to use the GPT-4 API but who knows how long access will take.

I think langchain might still be interesting combined with the CLI elements of chatgpt-wrapper, so chatgpt-wrapper might eventually like to integrate langchain in internals.

**Comment by thehunmonkgroup** [comment]
Link is busted, looks like they moved it: https://python.langchain.com/en/latest/modules/prompts/prompt_templates/examples/prompt_serialization.html

I've also researched Langchain, and have these observations:

* It does a lot of heavy lifting
* It's a lot to learn
* I'm currently unconvinced about the utility of their prompt templates
* The library doesn't do anything we need yet, in a way that's convinced me to migrate to it

We *do* have a dependency on Langchain, which I added to support the `zap` plugin, but that was mostly for fun.

It's certainly possible that leveraging Langchain will be a win long-term, but until it solves a real problem in this codebase, I don't want to pre-optimize.

As for the prompt templates, give me use cases that their implementation solves that our Jinja-based template system doesn't, in the context of the CLI functionality. I'm not crazy about their choice there, I think Jinja is a better choice. I know you can make Jinja work in Langchain via a custom prompt templates, but again, not seeing the direct benefit given our current functionality.

Feel free to enlighten me if I'm missing anything :)

**Comment by thehunmonkgroup** [comment]
I've integrated quite a few of the Langchain elements in the 0.9.0 release, like supporting multiple LLM providers, and saving/loading LLM configurations (via presets).

I remain unconvinced that Langchain's prompt templates are useful in the context of this project. IMO the current Jinja template approach is much better for our use cases -- the Langchain prompt templates seem more appropriate when doing more complex tasks directly in Python.
