### ISSUE TITLE
no attribute id

### ISSUE THREAD

**Issue by robertoberto** [mmabrouk/chatgpt-wrapper#262]
Several options I try in CLI same error:

`roberto@gpt-3.5-turbo 1> /switch 3

 • Fetching conversation history...                                                                                                                         

AttributeError("'NoneType' object has no attribute 'id'")
(0.9/1/0.6/0/4000/0)
roberto@gpt-3.5-turbo 1>

`

roberto@gpt-3.5-turbo 1> /title foo

 • Fetching conversation history...                                                                                                                         

AttributeError("'NoneType' object has no attribute 'id'")
(0.9/1/0.6/0/4000/0)

**Comment by thehunmonkgroup** [comment]
Cannot reproduce:

```
(0.5/1/0.6/0/4000/0)
hunmonk@gpt-3.5-turbo 1> /switch 3

 • Fetching conversation history...                                                                                                    

                                              Switched to: "Simple Python Plugin Manager"                                              

(0.5/1/0.6/0/4000/3023)
hunmonk@gpt-3.5-turbo 2>
```

This along with your earlier submission at https://github.com/mmabrouk/chatgpt-wrapper/discussions/260 suggest that you are not running an up to date version of the codebase, or you have a very old dependency in place.

Before reporting any more issues, please perform a complete reinstall of the package, **including all dependencies**. I would recommend doing this via a virtualenv.

**Comment by robertoberto** [comment]
hi thank you very much for your help
I am almost taking a look on source code to debug

but maybe it is something common

1) I create a new macos user callded dev
2) I am using brew python3.11
3) I am using virtualenv
4) these are pip modules inside virtualenv

(env) dev@MacOS-RB chatgpt-wrapper % pip list
Package            Version   Editable project location
------------------ --------- ----------------------------------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              22.2.0
certifi            2022.12.7
charset-normalizer 3.1.0
chatGPT            0.7.2     /Users/dev/chatgpt/chatgpt-wrapper
click              8.1.3
dataclasses-json   0.5.7
distlib            0.3.6
dnspython          2.3.0
email-validator    1.3.1
et-xmlfile         1.1.0
filelock           3.10.7
Flask              2.2.3
frozenlist         1.3.3
geojson            2.5.0
greenlet           2.0.1
idna               3.4
itsdangerous       2.1.2
Jinja2             3.1.2
langchain          0.0.125
markdown-it-py     2.2.0
MarkupSafe         2.1.2
marshmallow        3.19.0
marshmallow-enum   1.5.1
mdurl              0.1.2
multidict          6.0.4
mypy-extensions    1.0.0
names              0.3.0
numpy              1.24.2
openai             0.27.2
openpyxl           3.1.2
packaging          23.0
pip                23.0.1
platformdirs       3.2.0
playwright         1.32.0
prompt-toolkit     3.0.38
pydantic           1.10.7
pyee               9.0.4
Pygments           2.14.0
pyowm              3.3.0
pyperclip          1.8.2
PySocks            1.7.1
python-frontmatter 1.0.0
PyYAML             6.0
regex              2023.3.23
requests           2.28.2
rich               13.3.3
setuptools         67.4.0
SQLAlchemy         1.4.47
tenacity           8.2.2
tiktoken           0.3.3
tqdm               4.65.0
typing_extensions  4.5.0
typing-inspect     0.8.0
urllib3            1.26.15
virtualenv         20.21.0
wcwidth            0.2.6
Werkzeug           2.2.3
wheel              0.38.4
yarl               1.8.2


same problem yet
```

roberto@gpt-3.5-turbo 7> /title ola

 • Fetching conversation history...                                                                                                                         

AttributeError("'NoneType' object has no attribute 'id'")
(0.9/1/0.6/0/4000/22)                                                                                                                                       
roberto@gpt-3.5-turbo 7>                                   

```

and I cannot make chatgpt remember my name in conversations


```

roberto@gpt-3.5-turbo 1> /new

 • New conversation started.                                                                                                                                

(0.9/1/0.6/0/4000/0)
roberto@gpt-3.5-turbo 2> /ask meu nome é roberto

Olá Roberto, como posso ajudá-lo?

(0.9/1/0.6/0/4000/24)
roberto@gpt-3.5-turbo 3> /ask qual meu nome

Eu não sei qual é o seu nome. Qual é o seu nome?

(0.9/1/0.6/0/4000/21)

```

**Comment by thehunmonkgroup** [comment]
`chatgpt --version` please

**Comment by robertoberto** [comment]
(env) dev@MacOS-RB chatgpt-wrapper % chatgpt --version
/Users/dev/chatgpt/env/bin/chatgpt version 0.7.2

**Comment by fuckeversec** [comment]
![image](https://user-images.githubusercontent.com/47920283/230270214-20a36b00-8a4d-46ff-b266-ec70120d01d7.png)

chatgpt --version
/opt/homebrew/bin/chatgpt version 0.8.2

**Comment by thehunmonkgroup** [comment]
@fuckeversec great, this is progress, but I need a little more info:

1. It should not be possible to get to that point in the code without a `current_user` object. Could you please run `chatgpt --debug` to start the program, then run the exact series of commands that are causing that error, and include here?
2. I'd also like to see the output of these commands:
    * `/config database`
    * `/user`
    * `/users`

**Comment by fuckeversec** [comment]
![image](https://user-images.githubusercontent.com/47920283/230534871-5669e7d4-b007-4895-a0d7-cdaa99cc2330.png)
![image](https://user-images.githubusercontent.com/47920283/230534899-35d85307-3ac7-4520-8ea8-23b73cae55df.png)
![image](https://user-images.githubusercontent.com/47920283/230534926-efc0c6bd-57ad-44d7-b971-a1540bf783ca.png)

**Comment by thehunmonkgroup** [comment]
Should now be fixed in the latest release, the extra debugging info was helpful, thanks.
