### ISSUE TITLE
OpenAIError: The model: `gpt-4-32k-0314` does not exist

### ISSUE THREAD

**Issue by oushujun** [mmabrouk/chatgpt-wrapper#263]
Hello,

Thank you for making this great GPT API wrapper! I installed the wrapper using git+pip for version 0.7.2 in Linux. I can use the default model and the turbo models, but all gpt4 models are not usable. I have a plus account and already export OPENAI_API_KEY to $ENV. I also checked the OpenAI status, and nothing is down.

/model gpt4
                                default        
                                turbo          
                                turbo-0301     
                                gpt4           
                                gpt4-0314      
                                gpt4-32k       
                                gpt4-32k-0314

shujun@gpt-4 1> /model gpt4-32k-0314
Current model updated to: gpt-4-32k-0314

(0.9/1/0.6/0/4096/19)
shujun@gpt-4-32k-0314 1> test
AsyncOpenAIAPI - ERROR - OpenAIError: The model: `gpt-4-32k-0314` does not exist
OpenAIError(message=InvalidRequestError(message='The model: `gpt-4-32k-0314` does not exist', param=None, code='model_not_found', http_status=404, request_id=None), http_status=None, request_id=None)
(0.9/1/0.6/0/4096/19)

What might be the cause and how to use gpt4?

Thank you!
Shujun

**Comment by thehunmonkgroup** [comment]
The `chatgpt-api` backend uses OpenAI's API directly.

GPT-4 model access via the API is only available via the waitlist: https://openai.com/waitlist/gpt-4-api
