### ISSUE TITLE
Feature request: Read prompt from the clipboard and send it to ChatGPT

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#266]
Could we have something like a /clipboard or /readclipboard or /readclip or similar? This would pull the contents of the clipboard and send it to ChatGPT for processing.

**Comment by thehunmonkgroup** [comment]
I believe the current `{{ clipboard }}` builtin variable for templates already serves this purpose, and is more flexible:

https://github.com/mmabrouk/chatgpt-wrapper#builtin-variables
