### ISSUE TITLE
ValueError: PROFILE_DEFAULT_OPENAI_API_KEY or OPENAI_API_KEY environment variable must be set

### ISSUE THREAD

**Issue by AmanKabra** [mmabrouk/chatgpt-wrapper#271]
I'm new to this package - can you help out with the following error? I was under the impression that an OpenAI key would not be needed for this package as it uses the browser-based version of ChatGPT.

bot = OpenAIAPI()
Traceback (most recent call last):
  File "C:\Users\Aman\AppData\Local\Temp\ipykernel_28108\1047766777.py", line 1, in <module>
    bot = OpenAIAPI()
  File "C:\Users\Aman\Anaconda3\envs\randomstuff\lib\site-packages\chatgpt_wrapper\backends\openai\api.py", line 18, in __init__
    self._configure_access_info()
  File "C:\Users\Aman\Anaconda3\envs\randomstuff\lib\site-packages\chatgpt_wrapper\backends\openai\api.py", line 47, in _configure_access_info
    raise ValueError(f"{profile_prefix}_OPENAI_API_KEY or OPENAI_API_KEY environment variable must be set")
ValueError: PROFILE_DEFAULT_OPENAI_API_KEY or OPENAI_API_KEY environment variable must be set

**Comment by thehunmonkgroup** [comment]
Browser backend has been deprecated. See the README if you still want to use it.

**Comment by jmgomezpoveda** [comment]
> Browser backend has been deprecated. See the README if you still want to use it.

Is there any reason for this deprecation? I was using it successfully so far, and the OpenAI API is very expensive for small/hobby projects.

**Comment by thehunmonkgroup** [comment]
Remotely controlling a full browser instance on a completely unofficial website API has always been a brittle hack, as is evidenced by the large majority of bug reports in this project related to the approach.

The official OpenAI API for ChatGPT has been out for awhile now, is stable, and is fully supported by this project -- it's pretty clearly the best choice going forward in terms of stability and maintainability.

That being said, the browser backend is deprecated, but still present. While no support will be provided for direct Python implementations using its `ChatGPT` class, it is still in the codebase, and some support will still be provided for those using the shell backed by it.
