### ISSUE TITLE
identify code and make it in different color 

### ISSUE THREAD

**Issue by NateCC0902** [mmabrouk/chatgpt-wrapper#272]
as a software engineer, search a code questions are oftenly. 

make it in different color then nomal text color will be more readable.

Since openai api respond code in begin ''' and end with '''. 

i think its pretty easy to implement and i am willing to do it. let me know if its a possible feature.

**Comment by thehunmonkgroup** [comment]
Already implemented, you must either:

1. Use the non-streaming mode
2. Use the `/chat` command to reprint the conversation

I don't think it's practical to perform syntax highlighting during streaming, not in the shell.
