### ISSUE TITLE
Stream interruption not working, backend limitations

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#274]
The backends are not properly handling clean interruption of streamed responses, for different reasons:

 - ** API backend:** The Langchain LLM interface does not have a mechanism to cleanly interrupting streaming requests. I've filed https://github.com/hwchase17/langchain/pull/4403 with the project, and if that gets merged, it should start working again.
 - **Browser backend:** Despite best efforts, the `ctrl-c` signal causes the browser instance to close, which then requires force closing and restarting. Others have noticed this deficiency with Playwright, as is documented here: https://github.com/microsoft/playwright-python/issues/1170 -- but there seems to be no movement on a fix.

**Comment by blksith0** [comment]
I'm using the API backend, and Ctrl+C Used to work, but now...

```
(0.7/4096/0): default
dhyan@gpt-3.5-turbo 1> Hey don't give me a RateLimitError

Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
**^C^C**Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
**^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C**Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
**^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C**Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
**^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C**^Z
[12]+  Stopped                 chatgpt```

Ctrl+C bolded for your viewing pleasure.

**Comment by thehunmonkgroup** [comment]
@blksith0 see the original post, it links to the Langchain issue that's holding up this fix. Feel free to add your voice there :)

**Comment by thehunmonkgroup** [comment]
I've version locked Langchain, and monkey patched it to fix the issues with stream interruption.

Still working getting the upstream error fixed here: https://github.com/hwchase17/langchain/pull/4403

In better news, Playwright seems to have fixed the issue that was crashing things during stream interruption, so only the Langchain PR remains.
