### ISSUE TITLE
New Feature - *nix std input pipe logic support

### ISSUE THREAD

**Issue by ocontant** [mmabrouk/chatgpt-wrapper#277]
It would be convenient to be able to use *nix pipe support for the chatgpt binary to perform things like:

- cat filename.txt | chatgpt "Summarize the text"
- chatgpt "Summarize the text" < cat ${filename.txt}
- chatgpt read file ./filename.txt and Markdown
- chatgpt identify redundant information in the file ./filename.txt

Constraint:
- Limit of tokens per request. ChatGPT 4 will have a support for 32K 
- Split the prompt by iteration max_token per prompt interaction

Controls:
- Need to return an error if the size of text input is bigger than prompt max_token_size

Asking ChatGPT to help with this: 
What code would be required for chatgpt-wrapper to support input pipe like this command ?
```shell
$ chatgpt "Summarize this text" < ./Draft.txt
$ cat ./Draft.txt | chatgpt "Summarize this text"
```

To support input pipe like the command above (`cat file.txt | chatgpt "Summarize this text"`), you can modify the `chat()` method in the `ChatGPT` class of your `chatgpt-wrapper` code as follows:

```python
def chat(prompt):
    try:
        # Check if prompt is being passed via STDIN input pipe
        if not prompt:
            prompt = sys.stdin.read().rstrip()  # Read input from pipe
    except Exception as e:
        print(f"Error while reading from input pipe: {e}")
        return ""

    # Convert prompt to GPT-3 API format
    gpt3_prompt = format_prompt(prompt)

    # Send prompt to GPT-3 API and get response
    response = send_request(gpt3_prompt)

    # Extract text from response
    try:
        text = extract_text(response)
    except Exception as e:
        print(f"Error while extracting text from response: {e}")
        return ""

    # Return response text
    return text
```

This modification checks if the `prompt` argument is empty, which indicates that the input is being passed via STDIN input pipe. If it's empty, the function reads the input from the pipe using `sys.stdin.read().rstrip()`.

Note that this modification assumes that your `chatgpt-wrapper` code already handles the `prompt` argument passed to the `chat()` method when it's called directly (i.e. without the input pipe).

**Comment by thehunmonkgroup** [comment]
Please do not paste long responses generated by ChatGPT in this issue queue, it makes reading the issue more difficult, and any user can easily perform this themselves.

Can you please explain why you cannot use the existing `/file` command, or write your own simple wrapper around the Python module to perform this function?

**Comment by thehunmonkgroup** [comment]
In addition to @1core2life 's comments, I'm not sure if pipes are a good fit with this particular tool.

Don't get me wrong, I love the flexibility of the Unix pipe philosophy, but something feels off about it here, although I'm not able to articulate my concern yet.

**Comment by thehunmonkgroup** [comment]
Implemented with https://github.com/mmabrouk/chatgpt-wrapper/commit/f7e3cf54934ee22345578f9ca0528471181312d0 and https://github.com/mmabrouk/chatgpt-wrapper/commit/3b2915b231e07c6ec28cab2c8c48bf9e812914d5

```
chatgpt -i ~/Desktop/something.txt summarize this
```
