### ISSUE TITLE
Ignores model in config.yaml

### ISSUE THREAD

**Issue by Neil-Sawhney** [mmabrouk/chatgpt-wrapper#283]
runtime configuration verifies that the model in the runtime configuration is set to gpt-4, however on running 
chatgpt, the input is still gpt-3.5-turbo

**Comment by thehunmonkgroup** [comment]
The default model on the API backend is currently set per user -- the setting you're using in the config file is only valid for the `chatgpt-browser` backend.

I've updated the sample config to clarify this, and included instructions in the README for how to set the default model per user: https://github.com/mmabrouk/chatgpt-wrapper#setting-the-default-model

**Comment by Neil-Sawhney** [comment]
@thehunmonkgroup, makes perfect sense. Thank you!
