### ISSUE TITLE
Breaking change after deprecation of ChatGPT class

### ISSUE THREAD

**Issue by idilsulo** [mmabrouk/chatgpt-wrapper#285]
Hi! 

I have a question regarding the deprecation of `ChatGPT` class. I have seen that this had been updated to `OpenAIAPI` class instead. However, this resulted in a breaking change in my case when I consume the package inside my Python scripts.

Previously, when I was using the package in the following way, every time I asked a prompt to ChatGPT, it was resulting in a response within the same session, considering the conversation history.

```
from chatgpt_wrapper import ChatGPT

bot =  ChatGPT()

success, response1, message = bot.ask(prompt)  # first response

success, response2, message = bot.ask(prompt)  # response2 depends on response1

```

Now, each time a prompt is asked, it is considered to be in a separate session without having a relation to past conversation history, meaning that the following responses do **not** depend on the previous ones.

```
from chatgpt_wrapper import OpenAIAPI

bot =  OpenAIAPI()

success, response1, message = bot.ask(prompt)  # first response

success, response2, message = bot.ask(prompt)  # response2 does **not** depend on response1

```

How can I use the new version to achieve the same behavior as before?

Thanks a lot!

**Comment by monkeypants** [comment]
I changed mine to this and it worked:
```
try:
    from chatgpt_wrapper import ChatGPT
except ImportError:
    from chatgpt_wrapper import OpenAIAPI as ChatGPT
```

**Comment by idilsulo** [comment]
@monkeypants What you have suggested is not related to this issue at all. This issue is about a functionality change, not just a name change.

**Comment by thehunmonkgroup** [comment]
This is not really a breaking change, but instead a difference in the way the two backends operate.

With the browser backend, you're logged into the official ChatGPT website, and that app is doing the work to maintain conversation history.

The API backend must use inbuilt mechanisms to do the same, which the REPL (shell) makes use of. So you'll either need to:

1. Manage the conversation history yourself
2. Leverage the existing in-built mechanisms in the API backend

Number 2 requires a proper setup of the API backend, including a creation of the database, and at least one user added. With that, there is a simple mechanism to instantiate the `OpenAIAPI` class with a default user, see https://github.com/mmabrouk/chatgpt-wrapper/blob/main/tests/integration/test_api_backend_get_history.py for an example.

I haven't specifically tested the case of conversation history being preserved across multiple `ask` invocations, but I'm fairly confident that would work.

**Comment by idilsulo** [comment]
I'll give this a try, thanks a lot for the info!

**Comment by barryridge** [comment]
Try the following if you'd like to keep using the browser-based interface.

First, make sure you create/edit a `config.yaml` file in your `chatgpt-wrapper` profile directory.  You can get the location of that by typing `chatgpt config` in a terminal.  On my macOS system, it was located in `/Users/<username>/Library/Application Support/chatgpt-wrapper/profiles/default/`.  It should contain the following:

```yaml
backend: chatgpt-browser
```

```python
from chatgpt_wrapper.backends.browser.chatgpt import ChatGPT
from chatgpt_wrapper.core.config import Config

config = Config()  # Create a default config object
config.load_from_file()  # Load user config from file
config.set("browser.debug", False)  # Prevent browser from popping up - run it headless
bot = ChatGPT(config)
bot.launch_browser()

success, response1, message = bot.ask(prompt)
success, response2, message = bot.ask(prompt)
```

You can check if the config is using the correct backend with a call to `config.get()`.

**Comment by thehunmonkgroup** [comment]
@barryridge `Config()` loads the default config into the object, you shouldn't need to `load_from_file()` unless you want to make any adjustments using a config file. Also, `browser.debug` is `False` by default, that should not need to be set explicitly.

So probably the cleanest way entirely in code would be something like this:

```python
from chatgpt_wrapper.backends.browser.chatgpt import ChatGPT
from chatgpt_wrapper.core.config import Config

config = Config() 
config.set("backend", "chatgpt-browser")
bot = ChatGPT(config)
bot.launch_browser()

success, response1, message = bot.ask(prompt)
success, response2, message = bot.ask(prompt)
```

**Comment by thehunmonkgroup** [comment]
Actually, you don't need that `config.set("backend", "chatgpt-browser")` since you're instantiating the class directly -- have a look at how the integration test at https://github.com/mmabrouk/chatgpt-wrapper/blob/main/tests/integration/test_browser_backend_non_streaming.py does it.

**Comment by thehunmonkgroup** [comment]
`load_from_file()` should only be needed if you want to, well, load configuration from a file :)

IMO when leveraging the Python module it's cleaner to operate on the `config` object.
