### ISSUE TITLE
Rate limited despite being on ChatGPT Plus plan

### ISSUE THREAD

**Issue by reppie** [mmabrouk/chatgpt-wrapper#286]
Hello!  Was very excited to try out this wrapper, so I purchased a Plus plan to make use of as much of the functionality as possible. However, when I enter the interactive mode, I am still getting rate limited:

```
(0.9/1/0.6/0/4000/0)
reppie@gpt-3.5-turbo 1> hello

Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
RateLimitError(message='You exceeded your current quota, please check your plan and billing details.', http_status=429, request_id=None)
(0.9/1/0.6/0/4000/19)
```

I've tried:
- The other models, but for `turbo-1` and `turbo-0301` the rate limit remains, and for any of the `gpt4` related ones I am getting an error that the model does not exist.
- Generating a new API KEY after getting the Plus subscription, but seemed to make no difference
- Try an invalid API KEY to make sure it was picking it up correctly, but I got a correct "invalid API KEY" response then

Any idea what I might be doing wrong and/or how I could get this to work?

EDIT (to include version):
```
❯ chatgpt --version
/Library/Frameworks/Python.framework/Versions/3.10/bin/chatgpt version 0.8.3
```

**Comment by thehunmonkgroup** [comment]
You're using the API backend, which interacts directly with the OpenAI API. That has nothing to do with ChatGPT Plus.

You'll need to switch to the browser backend, which accesses the ChatGPT web app.

**Comment by reppie** [comment]
Ahh thank you! I misunderstood the README :) Thank you, it works now!
