### ISSUE TITLE
Browser backend: 403 Forbidden on all non-chat requests

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#290]
Looks like OpenAI made a change to their security procedures on `chat.openai.com` -- all `GET`/`POST`/`PATCH` requests are failing for me, including:

* Getting history
* Getting/setting title
* Getting messages from chat
* Deleting conversation

I poked around a bit, but was not able to find the issue yet.

Feel free to post ideas or fixes.

**Comment by thehunmonkgroup** [comment]
Looks like a CAPTCHA is getting triggered on their Cloudflare front end:

```html
<form id="challenge-form" class="challenge-form"
				action="/backend-api/conversations?offset=0&amp;limit=20&amp;__cf_chl_f_tk=abBm88R4UGqIsGmKMbPbsUnHSrAwCp76lrHxC2ILIFQ-1681869053-0-gaNycGzNDvs"
				method="POST" enctype="application/x-www-form-urlencoded">
				<div id="cf-please-wait">
					<div id="spinner">
						<div id="cf-bubbles">
							<div class="bubbles"></div>
							<div class="bubbles"></div>
							<div class="bubbles"></div>
						</div>
					</div>
					<p id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
					<p id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
				</div>
				<input type="hidden" name="md" value="..." />
				<noscript id="cf-captcha-bookmark" class="cf-captcha-info">
					<h1 style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
				</noscript>
				<div id="no-cookie-warning" class="cookie-warning" style="display:none">
					<p style="color:#bd2426;">Please enable Cookies and reload the page.</p>
				</div>
				<div id="trk_jschal_js"
					style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7ba17fd2d89cec5c')">
				</div>
			</form>
```
Not really sure how to get around this, as the CAPTCHA isn't getting triggered on login.

**Comment by thehunmonkgroup** [comment]
Also tried `chatgpt reinstall` to get a completely fresh browser profile, no luck.

**Comment by jobez** [comment]
this happens intermittently for me. it briefly went away yesterday, but now it returns. i primarily run into this when i want to switch conversations--is there a way to get the last message id from the debug playwright browser and set it manually?

**Comment by thehunmonkgroup** [comment]
> is there a way to get the last message id from the debug playwright browser and set it manually?

probably not. you can pass the conversation UUID to `/switch`, and that will bypass loading the conversation history, but it still makes a call to the server before it switches the conversation in the backend.

**Comment by zhirafovod** [comment]
Same error on my side. I could not find a workaround so far. 

1. Run chatgpt from main branch with browser debug
```
chatgpt -d
```
it starts Nighly browser in foreground, and loads the page
2. Refresh session successfully
```
text-davinci-002-render-sha 1> /session
ChatGPT - INFO - Refreshing session...
ChatGPT - DEBUG - Refreshing session received: {...}
ChatGPT - INFO - Succeessfully refreshed session.
```
3. attempt to fetch history consistently fails with http 403 error
```
text-davinci-002-render-sha 1> /history

 • Fetching conversation history...

ChatGPT - INFO - Refreshing session...
ChatGPT - DEBUG - Refreshing session received: {...}
ChatGPT - INFO - Succeessfully refreshed session.
ChatGPT - DEBUG - GET https://chat.openai.com/backend-api/conversations request, query params: {'offset': 0, 'limit': 20}, headers: {'Authorization': 'Bearer <redacted>'}
ChatGPT - DEBUG - GET https://chat.openai.com/backend-api/conversations response, OK: False, TEXT: <html>
  <head>
    <style global>body <...blahblahblah..>
 ChatGPT - DEBUG - 403 Forbidden {'date': 'Wed, 26 Apr 2023 18:15:57 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'cross-origin-embedder-policy': 'require-corp', 'cross-origin-resource-policy': 'same-origin', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cf-mitigated': 'challenge', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '7be0d06b5f9e176d-SJC', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
ChatGPT - ERROR - Failed to get history: 403 Forbidden
Failed to get history: 403 Forbidden
```

Will appreciate any help on it.

**Comment by thehunmonkgroup** [comment]
The browser backend is getting harder to maintain, and the less support it gets from the community (via pull requests or funding sponsorship), the more chance it's going to die.

So consider pitching in if you'd like it to survive :)

**Comment by thehunmonkgroup** [comment]
@jobez @zhirafovod can you upgrade to 0.9.0 release and re-test?

I've moved the `GET/PATCH/POST` API commands to execute via XHR requests, and everything is now working perfectly for me.

Note that 0.9.0 is a substantial rewrite, be sure to check the `Breaking changes` at https://github.com/mmabrouk/chatgpt-wrapper/releases/tag/v0.9.0 for any config/etc. changes.

**Comment by tavisrudd** [comment]
@thehunmonkgroup that fixed the same issue for me. Thanks!

**Comment by zhirafovod** [comment]
Wow, this is cool. You are a true JS ninja @thehunmonkgroup . What is next ambitious project - bard browser backend support? :)

**Comment by thehunmonkgroup** [comment]
> Wow, this is cool. You are a true JS ninja @thehunmonkgroup .

Gotta give GPT-4 most of the credit on the code. I mean, who *writes code* anymore?

> What is the next ambitious project - Bard browser backend support?

No f*ing way... ;) Not without sponsorship, anyways. The browser backend is a nightmare. But it seems right to keep the original one going until OpenAI fatally wounds it.

**Comment by thehunmonkgroup** [comment]
Given the feedback, I'm going to consider this issue solved. Reopen if anyone is still having issues.
