### ISSUE TITLE
ChatGPT4

### ISSUE THREAD

**Issue by avijay6** [mmabrouk/chatgpt-wrapper#292]
Is ChatGPT 4 working for any of you? Mine it says "gpt4 doesnt exist"

**Comment by thehunmonkgroup** [comment]
https://github.com/mmabrouk/chatgpt-wrapper#gpt4

**Comment by avijay6** [comment]
I tried this but it says doesnt exist

**Comment by thehunmonkgroup** [comment]
I have updated https://github.com/mmabrouk/chatgpt-wrapper#gpt4 with more clear instructions, and fixed a few small errors.

Most likely your issue is that you're using the API backend, and you have not been granted API access from OpenAI to GPT-4 yet.

**Comment by avijay6** [comment]
Yes, thats right,m. I am still on the gpt4 api waitlist

On Sun, Apr 23, 2023 at 11:26 AM thehunmonkgroup ***@***.***>
wrote:

> I have updated https://github.com/mmabrouk/chatgpt-wrapper#gpt4
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmmabrouk%2Fchatgpt-wrapper%23gpt4&data=05%7C01%7Cavijay6%40groute.uic.edu%7Cb5b0fe0e8b9f48bb42fc08db441787b7%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638178640074350900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tVP645N2Iv%2FjQbejdbRSwiWajo7uIG8RBPc4%2BSY%2BKXg%3D&reserved=0>
> with more clear instructions, and fixed a few small errors.
>
> Most likely your issue is that you're using the API backend, and you have
> not been granted API access from OpenAI to GPT-4 yet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmmabrouk%2Fchatgpt-wrapper%2Fissues%2F292%23issuecomment-1519104665&data=05%7C01%7Cavijay6%40groute.uic.edu%7Cb5b0fe0e8b9f48bb42fc08db441787b7%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638178640074350900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LhiNypvC43XwbRObYk3OY05DqX5gdcuCGew1Js4qOw8%3D&reserved=0>,
> or unsubscribe
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGQK25ENLIDDSY2XJHNC4S3XCVJ4LANCNFSM6AAAAAAXIHNMTA&data=05%7C01%7Cavijay6%40groute.uic.edu%7Cb5b0fe0e8b9f48bb42fc08db441787b7%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638178640074350900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E%2BTCHtynwoWN4ZZaCKFQqyEsR74k1ccm8ekeKEic8Qg%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
-- 
Regards

Aishwarya
PhD Student
Computer Science and Engineering
UIC
