### ISSUE TITLE
is chatgpt-wrapper formatting text somehow?

### ISSUE THREAD

**Issue by kurokirasama** [mmabrouk/chatgpt-wrapper#294]
Testing things out I tried this prompt:

Please translate the following text to Spanish, and return only the translated text as the output, without any additional comments or formatting. Keep the same capitalization (in every word) and punctuation as the original text. The text to translate is: hello, my dear friend

And chatgpt-wrapper returns: Hola, mi querido amigo.
While web chatgpt returns: hola, mi querido amigo

How can I get the second output from chatgpt-wrapper?

**Comment by thehunmonkgroup** [comment]
The wrapper returns the output exactly as it's received from OpenAI.

I suspect you're just seeing variance in ChatGPT's output itself.

**Comment by thehunmonkgroup** [comment]
```
hunmonk@gpt-3.5-turbo 23> Repeat this exact phrase, all lower case: hello, my dear friend

hello, my dear friend
```
