### ISSUE TITLE
Deploy `chatgpt-wrapper` as APIs on local/cloud using langchain-serve?

### ISSUE THREAD

**Issue by deepankarm** [mmabrouk/chatgpt-wrapper#295]
Great work on the chatgpt wrapper!

[langchain-serve](https://github.com/jina-ai/langchain-serve) can help by figuring out the API deployment both locally & on cloud (making the APIs ready on Production from current experimental ones).

Highlights:
- Exposes APIs from function definitions locally as well as on the cloud.
- Very few lines of code changes and ease of development remain the same as local.
- Supports both REST & WebSocket endpoints with custom authorization.
- Serverless/autoscaling endpoints with automatic tls certs on the cloud.
- Real-time streaming, human-in-the-loop support - crucial for chatbots.

Disclaimer: I'm the primary author of langchain-serve. Would be happy to collaborate on this.

**Comment by thehunmonkgroup** [comment]
This seems like marketing/promotional, and not really appropriate for the issue queue.

In the future, please put things like this at https://github.com/mmabrouk/chatgpt-wrapper/discussions
