### ISSUE TITLE
Add a quick command for the new "Continue generating" button

### ISSUE THREAD

**Issue by blksith0** [mmabrouk/chatgpt-wrapper#305]
ChatGPT web UI has a new feature:
https://preview.redd.it/3rkh8bkhm50b1.png

Let's add a little quick command, maybe `/c` so I don't have to type "continue" over and over.

**Comment by 1core2life** [comment]
I think it's the same approach as #151  issue :)

**Comment by blksith0** [comment]
I ended up just typing `\ ` and it works the same.
