### ISSUE TITLE
stuck with "Verify you are a human"

### ISSUE THREAD

**Issue by delip** [mmabrouk/chatgpt-wrapper#31]
I keep getting this, even after clicking the blue button. I am guessing this is because Playwright opens this with the chromium window. How do I make this open with my usual Safari browser?

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/347398/207237036-1739f981-d948-4936-acd6-709365870d9c.png">

**Comment by Tecuya** [comment]
I added a `-b` parameter that you can use to choose a different browser.  You can choose 'firefox' 'chromium' or 'webkit'.  webkit is the one thats closest to safari.  I've verified that firefox and chromium can work, but I've not tried webkit yet

**Comment by MothBuzzing** [comment]
I also got stuck in the "verify you are a human" page. I've clicked the verify button for thousands of times, still could not get to the login page.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/119860790/224360220-bff86752-aa61-4119-a7b6-0d2a91210b57.png">
