### ISSUE TITLE
I would like to reference a previous answer 

### ISSUE THREAD

**Issue by HanadS** [mmabrouk/chatgpt-wrapper#317]
Here is my code. I would like to be able to reference the response in a follow up question. When I print I get ''No current user, conversation not saved'. Do I need to create a user in order to do this. If so, how do I do that? 

```
config = Config()
config.set('browser.debug', True)
bot = ApiBackend(config)
success, response, message = bot.ask(question)

if not success:
    raise RuntimeError(message)
```

**Comment by thehunmonkgroup** [comment]
See this test: https://github.com/mmabrouk/chatgpt-wrapper/blob/main/tests/integration/test_api_backend_get_history.py

You should also be able to pass the username as a string instead of the user ID.
