### ISSUE TITLE
Option to disable the metadata after chat response?

### ISSUE THREAD

**Issue by joshcho** [mmabrouk/chatgpt-wrapper#320]
**Is your feature request related to a problem? Please describe.**
I think it's sensible to include an option to disable the metadata (i.e. temperature, token count) after each chat response. Right now for me, every chat response is appended with "(0.7/8192/54): default".

**Describe the solution you'd like**
Just a simple config that allows this to be turned off.

**Comment by thehunmonkgroup** [comment]
Customizing the shell prefix is documented in the sample config: https://github.com/mmabrouk/chatgpt-wrapper/blob/main/config.sample.yaml
