### ISSUE TITLE
chatgpt install fails

### ISSUE THREAD

**Issue by ifuchs** [mmabrouk/chatgpt-wrapper#34]
I tried following the install instructions and when I say chatgpt install, a browser window appears for an instant and I get the following in the console:
playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"

**Comment by Tecuya** [comment]
Weird, I've never seen this.  It seems that firefox is rejecting the cert that its finding on https://chat.openai.com .. are you on a network that intercepts https with its own cert?  Are you able to load https://chat.openai.com using your normal everyday web browser?

Maybe you can try using chromium instead?  Run `chatgpt -b chromium install` to try it with chromium.  If that works, you'll need to use the `-b chromium` parameter every time you run `chatgpt`

**Comment by ifuchs** [comment]
When I try the chromium install, chromium opens and I get into a never ending verification loop about whether I am human:
chat.openai.com
Checking if the site connection is secure

chat.openai.com needs to review the security of your connection before proceeding.

**Comment by ifuchs** [comment]
I tried opening Chromium by itself and it has no trouble authenticating to chat.openai.com. However, when driven by the chatgpt program it will not verify as human. Perhaps this no longer works.

**Comment by fluturak** [comment]
i see the same problem, when chatgpt install, it opens the browser and closes with the error

**Comment by UriZafrir** [comment]
I have exactly the same problem.

**Comment by thehunmonkgroup** [comment]
No reports of this issue for a long time, plus the browser backend is deprecated. Closing.
