### ISSUE TITLE
commands are too easy to use accidentally

### ISSUE THREAD

**Issue by Tecuya** [mmabrouk/chatgpt-wrapper#36]
If someone provides a prompt like:

`new cars are safer than old cars right?`

or

`session tracking in php is easy, right?`

It's going to accidentally be triggering the `new` command, and the `session` command.

But what's the solution?  Do we make all commands require a fore slash or something?  `new` becomes `/new`? 

Does anyone have an opinion, is it worth changing?

**Comment by kylrth** [comment]
If you're seeking opinions, mine would be to prepend with a slash. Ambiguity bad

**Comment by mmabrouk** [comment]
I also agree with requiring slashes

**Comment by thehunmonkgroup** [comment]
implemented long ago, command leader is forward slash now.
