### ISSUE TITLE
Open previous session

### ISSUE THREAD

**Issue by Croug** [mmabrouk/chatgpt-wrapper#38]
With the introduction of chat history you can now resume an old session, are there any plans to add support for this?

**Comment by Tecuya** [comment]
When you enable logging, the log has context strings written to it.  You can load these contexts using the `context` command.

**Comment by josiahzimm** [comment]
@Tecuya is this also a feature for the API, or is it just the shell program? I didn't see any options or arguments that the ChatGPT class accepts that would allow for logging / context restoring, but maybe I am missing something there.

**Comment by mmabrouk** [comment]
This is more of a feature of the shell. It should be easy to integrate in the python part. I don't have currently time to do it, however any PR would be welcome :)

**Comment by zkiihne** [comment]
I wrote this method to load the context in my application using the chatgpt-wrapper. It is pretty generic so you should be able to use it easily.    
    
    def load_context(self, context_id):
        try:
            (conversation_id, parent_message_id) = context_id.split(":")
            assert conversation_id == "None" or len(conversation_id) == 36
            assert len(parent_message_id) == 36
        except Exception as e:
            print(e)
            raise
        if conversation_id == "None":
            conversation_id = None
        self.chatGPTBot.parent_message_id = parent_message_id
        self.chatGPTBot.conversation_id = conversation_id

**Comment by Shuangcheng-Ni** [comment]
> I wrote this method to load the context in my application using the chatgpt-wrapper. It is pretty generic so you should be able to use it easily.
> 
> ```
> def load_context(self, context_id):
>     try:
>         (conversation_id, parent_message_id) = context_id.split(":")
>         assert conversation_id == "None" or len(conversation_id) == 36
>         assert len(parent_message_id) == 36
>     except Exception as e:
>         print(e)
>         raise
>     if conversation_id == "None":
>         conversation_id = None
>     self.chatGPTBot.parent_message_id = parent_message_id
>     self.chatGPTBot.conversation_id = conversation_id
> ```

How can I get the **uuid** of a certain message (i.e. `parent_message_id`) by pressing F12 to inspect the website in a browser?

**Comment by Shuangcheng-Ni** [comment]
> You can look under the Network tab after pressing F12. iirc the payload for the conversation request will have it

It works well. Thanks a lot!
Is it possible to get the `parent_message_id` of previous messages? It seems that this method only works on newly generated messages.

**Comment by thehunmonkgroup** [comment]
`/history` and `/switch` commands implemented long ago in the shell.
