### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by karimk123** [mmabrouk/chatgpt-wrapper#40]
After only a few commands, i get the "Unusable response produced by ChatGPT, maybe its unavailable."

So then i try again but from the actual browser it says i can try again in 1 hour. Is there a way to bypass this ? 
I want to use this as an API for my web app so anyone on there could try it and input a command but if its getting rate limited like this its not going to work,

**Comment by mindgitrwx** [comment]
I guess the rate limiting is the result of Cloudflare, and it can't be bypassed by nature. 
https://support.cloudflare.com/hc/en-us/articles/115001635128-Configuring-Cloudflare-Rate-Limiting

ChatGPT is $100,000 per day. Highly recommend you read this article.
https://indianexpress.com/article/technology/tech-news-technology/chatgpt-interesting-things-to-know-8334991/

All we can to do is make a proper error message like 'Two many requests in 1 hour'

**Comment by karimk123** [comment]
i think i've seen some other chatgpt wrappers bypass cloud flare though it has to be possible. And now for reason i'm getting this message after only 1 prompt, so this is unusual.

**Comment by mmabrouk** [comment]
It looks you overused the wrapper. There is a daily limit per user. One solution would be to create multiple users using multiple ips. Another is to wait for the official api or use the gpt3 api

**Comment by bigbruno** [comment]
I have this problem, but just in https://chat.openai.com/api/auth/session
If use directly in browser work fine
