### ISSUE TITLE
Ctrl + D (to exit) sends EOF char to ChatGPT

### ISSUE THREAD

**Issue by kylrth** [mmabrouk/chatgpt-wrapper#41]
I tried using Ctrl + D to exit the REPL, and was surprised to see a description of the EOF character instead:

```txt
9> 
EOF stands for "end of file." It is a special character or sequence of characters that signifies the end of a file, input stream, or output stream. In programming, EOF is often used to indicate the end of a file when reading it, or the end of data when writing to a file. When an EOF character is encountered, the program may stop reading or writing, or it may take some other action, depending on how it is designed to handle EOF.
```

The REPL should exit when it receives EOF.

**Comment by mmabrouk** [comment]
ctrl-d is currently used in read mode (where you can paste stuff and write multiline) to prompt chatgpt. I agree that it could be confusing, but I think it is not a big issue especially since you can close with ctrl-c or using the command exit. I am closing therefore the issues
