### ISSUE TITLE
Threading Error, Please Help

### ISSUE THREAD

**Issue by CorruptCreeper** [mmabrouk/chatgpt-wrapper#47]
Starting a thread with bot.ask in it causes the script to crash with
greenlet.error: cannot switch to a different thread

```
import threading
import queue
from chatgpt_wrapper import ChatGPT
bot = ChatGPT()
running = True
text_input = ""
# Define a function for the AI processing
def run_ai_processing(response_queue, text_input):
    # Perform the AI processing using the text input
    response = bot.ask("Hello World!")

    # Put the response in the queue
    response_queue.put(response)

# Create a queue for the responses
response_queue = queue.Queue()

# Create a new thread for the AI processing, passing the text input as an argument
ai_thread = threading.Thread(target=run_ai_processing, args=(response_queue, text_input))

# Start the AI processing thread
ai_thread.start()

# Continue with your main game loop
while running:
    # Get the text input from the user
    text_input = input("Enter your text: ")

    # Start the AI processing thread with the new text input
    ai_thread = threading.Thread(target=run_ai_processing, args=(response_queue, text_input))
    ai_thread.start()

    # Check if there is a response in the queue
    if not response_queue.empty():
        # Get the response from the queue
        response = response_queue.get()
        pass
    response(print)
    # Your game code here
    pass

Heres the script in its entirety
```

Entire Thread Error
`Enter your text: Exception in thread Thread-1 (run_ai_processing):
Traceback (most recent call last):
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Olive\Downloads\ThreadingError.py", line 10, in run_ai_processing
    response = bot.ask("Hello World!")
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\site-packages\chatgpt_wrapper\chatgpt.py", line 230, in ask
    response = list(self.ask_stream(message))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\site-packages\chatgpt_wrapper\chatgpt.py", line 95, in ask_stream
    self.refresh_session()
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\site-packages\chatgpt_wrapper\chatgpt.py", line 60, in refresh_session
    self.page.evaluate(
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 8362, in evaluate
    self._sync(
  File "C:\Users\Olive\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_sync_base.py", line 102, in _sync
    self._dispatcher_fiber.switch()
greenlet.error: cannot switch to a different thread
`

**Comment by mariusnita** [comment]
Can't speculate on the root cause, but I would recommend that you put the constructor in the thread too.  Something like:

```py
def thread(input_queue, output_queue, stop_event):
  gpt = ChatGPT()
  while True:
    try:
      prompt = input_queue.get(timeout=1)
    except Empty:
      if stop_event.is_set():
        return

    reply = gpt.ask(prompt)
    output_queue.put(reply)
    
    
input_q = Queue()
output_q = Queue()
stop_event = Event()
t = Thread(target=thread, args=(input_q, output_q, stop_event))
t.start()

input_q.put("Write a poem")
reply = output_q.get()
print(reply)
  
# stop the thread
stop_event.set()
t.join()
```

So instead of spawning one thread per prompt, you have a long-running thread that does all the communication with GPT.

**Comment by CorruptCreeper** [comment]
So i rewrote the script with this in mind, and it now comes up with this error. I restarted my computer, reinstalled chatgpt using chatgpt install. The command chatgpt works as intended, it seems to only be this script that causes this. Any idea whats wrong?

**Comment by brandonrobertz** [comment]
This is the same problem as: https://github.com/mmabrouk/chatgpt-wrapper/issues/77

Playwright isn't thread safe. You need to create ChatGPT wrapper inside of each thread.

The README needs to state something about this IMO.

**Comment by thehunmonkgroup** [comment]
Browser backend is deprecated, and not supported for these use cases any more.
