### ISSUE TITLE
Typing "chatgpt install" does not come up with the web page display

### ISSUE THREAD

**Issue by ajtta** [mmabrouk/chatgpt-wrapper#52]
C:\Users\jtt>chatgpt install
> 12

> ERROR: No access token. Please, provide an access_token or email and password through the constructor/config file.
> w

> ERROR: No access token. Please, provide an access_token or email and password through the constructor/config file.
>

**Comment by mmabrouk** [comment]
It seems you had another library installed with the same name. Try removing it and reinstalling this library and the problem should be solved
