### ISSUE TITLE
Can we have some kind of indication that the program has started receiving a hopefully usable response?

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#54]
Several times I've sent a prompt to ChatGPT only for it to just sit there until I Ctrl+C to kill it. It would be nice to either have some kind of indication that a response is being received, or have the program give up after not receiving anything for a while.

**Comment by Robiemaan** [comment]
+1
Also, it seems the CLI interface with `stream` turned on waits with displaying the message until the chat.openai.com response is fully generated. Long responses take >20seconds.

**Comment by mmabrouk** [comment]
I made two fixes that solve the problem:
1) Now the cli per default streams the output of chatgpt live. So you can see whether it is responding or whether the program is waiting
2) I added a 60s timeout. If no response is returned within 60s the program breaks and outputs an error message. It is then your responsability to either try again, or try reauthentificating
