### ISSUE TITLE
zsh "no matches found" when `?` part of question

### ISSUE THREAD

**Issue by aidan-gibson** [mmabrouk/chatgpt-wrapper#55]
When running from zsh shell, chatgpt will not run if a question mark is part of the query.

```
chatgpt what is six times six?
zsh: no matches found: six?
```
My temp fix is setting `alias chatgpt="noglob chatgpt"` in my zshrc.

**Comment by mmabrouk** [comment]
Thanks for the issue and your solution!

Another solution is using it with escape character:

chatgpt "what is six time six?"
Six times six is 36.

chatgpt what is six time six\?
Six times six is 36.

I don't see a solution for the problem from the code itself
