### ISSUE TITLE
Feature Request: Support for image generation OpenAI API method

### ISSUE THREAD

**Issue by STARKBOND** [mmabrouk/chatgpt-wrapper#57]
Hello! Thanks everyone for all your work on this project. I'm a little naive, but I purely wanted to encourage you that one feature that I would especially be interested to see is OpenAI image generation support.

**Comment by mmabrouk** [comment]
This project provides a wrapper for the chatgpt website and does not use the openai api. Please check automatic1111 sd-webui repository if you are interested in image generation
