### ISSUE TITLE
Playwright sync vs Async Error

### ISSUE THREAD

**Issue by pjahoorkar** [mmabrouk/chatgpt-wrapper#7]
I'm getting the following error when I try to run 

from chatgpt_wrapper import ChatGPT
chatbot = ChatGPT()

Starting ... 
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6fe4e830-a918-4d07-9f50-8115c26780a3)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In [1], line 4
      1 from chatgpt_wrapper import ChatGPT
      2 import asyncio
----> 4 chatbot = ChatGPT()

File c:\Users\<>\miniconda3\lib\site-packages\chatgpt-0.1.0-py3.9.egg\chatgpt_wrapper\chatgpt.py:30, in ChatGPT.__init__(self, headless, timeout)
     28 self.timeout = timeout
     29 self.last_msg = None
---> 30 self.play = sync_playwright().start()
     31 self.browser = self.play.chromium.launch_persistent_context(
     32     user_data_dir=f"/tmp/playwright",
     33     headless=headless,
     34 )
     35 self.page = self.browser.new_page()

File c:\Users\<>\miniconda3\lib\site-packages\playwright-1.28.0-py3.9-win-amd64.egg\playwright\sync_api\_context_manager.py:95, in PlaywrightContextManager.start(self)
     94 def start(self) -> SyncPlaywright:
---> 95     return self.__enter__()

File c:\Users\<>\miniconda3\lib\site-packages\playwright-1.28.0-py3.9-win-amd64.egg\playwright\sync_api\_context_manager.py:44, in PlaywrightContextManager.__enter__(self)
     42             self._own_loop = True
     43         if self._loop.is_running():
---> 44             raise Error(
...
     56             and isinstance(asyncio.get_child_watcher(), asyncio.SafeChildWatcher)
     57         ):

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by azayz** [comment]
same issue for me

**Comment by mmabrouk** [comment]
I am aware of the error. I am using playwright in sync mode for now, however it should be modified to work async. I will try to fix it the next couple of days. PRs in the meantime are welcome :)

**Comment by Ghani-25** [comment]
same issue

**Comment by pjahoorkar** [comment]
I realized it's got to do with Jupyter Notebook. Apparently, jupyter needs an async call and so the sync call doesn't work. The command line works perfectly. This support above.

**Comment by kenngkz** [comment]
I am getting the same error from command line as well. 

I ran `chatgpt install`, logged in on the popup and clicked through disclosure boxes, then went back to the command line (without closing the popup) and pressed enter.

Then waited for awhile before the error was thrown. The error traceback is identical to the one at the top.

**Comment by parshinsh** [comment]
I also face the same error

**Comment by dcasota** [comment]
`chatgpt install` requires that the system has browser functionality. A class separation for e.g. `--use-device-code` would be helpful to use the tool on minimal os as well.

**Comment by NachoGarciaBajo** [comment]
Im getting the same error, have you found a workaround until the code is moved to async?

Thanks in advance!

**Comment by mmabrouk** [comment]
Just wanted to pop up to say that I don't see the code being moved to async for the medium term (I am overloaded at work), unless someone nice does the PR for us :)

**Comment by pfontana77** [comment]
Hello,
i also have the async API error. Just to understand, there' a workaround to use the class inside a program or is only usable by console using chatgpt.exe?

Thanks.

**Comment by ibehnam** [comment]
Do we have an update on this? I still get the async/sync error in Python.

**Comment by Ted8000** [comment]
anyone solved this?

**Comment by thehunmonkgroup** [comment]
1. Async support has been removed, this may solve some of the more recent reports.
2. The browser backend is deprecated, and its module usage is no longer supported, use the API backend module instead
