### ISSUE TITLE
Installation (or setup) needs pyreadline3

### ISSUE THREAD

**Issue by claell** [mmabrouk/chatgpt-wrapper#72]
On my machine, I needed to install `pyreadline3` with `pip` before I could run the `chatgpt install` command.

**Comment by claell** [comment]
Also, what happens there? Is this only relying on cookies or stores the credentials somewhere?

**Comment by rustybladez** [comment]
> On my machine, I needed to install `pyreadline3` with `pip` before I could run the `chatgpt install` command.

Man, you're a lifesaver. I spent hours trying to figure out why it wasn't working. I installed playwright and rich manually and still no progress. This fixed my issue.

**Comment by djfletcher** [comment]
+1 same

**Comment by SuperKenVery** [comment]
This issue seems to be solved now. I can see `pyreadline` in `requirements.txt`.

**Comment by udps** [comment]
I want to include an additional package that was necessary in my scenario to ensure successful installation. I hope this information proves useful for others encountering a similar issue in the future.

`apt libreadline-dev`

The aforementioned solution was derived from the original error that I encountered.

```Building wheel for readline (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ufrxqrhm/readline/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ufrxqrhm/readline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ljwtoaf4
       cwd: /tmp/pip-install-ufrxqrhm/readline/
  Complete output (612 lines):
  
  
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ufrxqrhm/readline/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ufrxqrhm/readline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2f70pje2/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/<user>/.local/include/python3.8/readline Check the logs for full command output.```

**Comment by thehunmonkgroup** [comment]
Fixed, moved to Prompt Toolkit
