### ISSUE TITLE
try/except on bad response

### ISSUE THREAD

**Issue by olegchomp** [mmabrouk/chatgpt-wrapper#73]
Hi! I saw that now wrapper response with message that it can't get response from ChatGPT. But now i wan't to handle this response, so something like:
`try: bot.ask(text) except: bot = ChatGPT() ....` 
can you advice a way to handle this, because if i do so, i get async error.

**Comment by thehunmonkgroup** [comment]
Unclear what you're asking for, if you could provide more explanation I may have feedback.
