### ISSUE TITLE
TimeoutError: Timed out while waiting for the response

### ISSUE THREAD

**Issue by karunakaruna** [mmabrouk/chatgpt-wrapper#8]
Windows 10 and MacOS:
TimeoutError: Timed out while waiting for the response

Perhaps the issue comes from the chatgpt Install
I log-in but no 'cookies' popup occurs.

**Comment by dylanbud** [comment]
Am also getting a timeout here, would be nice to output response status to the terminal if hung up

**Comment by Tecuya** [comment]
Let me know if you continue to see these issue occuring in version beyond 0.3.0 .. I pretty heavily refactored the way we read conversation responses from ChatGPT and hopefully those changes have had a positive impact here

**Comment by mmabrouk** [comment]
I assume the problem is solved. I added an additional timeout when openai don't provide a response after 60 seconds, after which the user can either exit or try again.
