### ISSUE TITLE
Can't install due to playwright installation issue

### ISSUE THREAD

**Issue by serenalotreck** [mmabrouk/chatgpt-wrapper#80]
When running `pip install git+https://github.com/mmabrouk/chatgpt-wrapper`, I get the following error:
```
ERROR: Could not find a version that satisfies the requirement playwright (from chatgpt) (from versions: none)
ERROR: No matching distribution found for playwright
```
I tried installing playwright directly via the instructions in their [docs](https://playwright.dev/python/docs/intro), but get the same error about not being able to find a distribution. I assume that this is a problem on playwright's end, but I wanted to ask it here because it seems like plenty of folks have gotten this installed and up and running.

Thanks!

**Comment by peterantonarosjr** [comment]
pip install playwright?

**Comment by tynguyen** [comment]
Run 
`pip install playwright`

or 
`python3 -m pip install playwright`
Then reinstall.
