### ISSUE TITLE
No answer shows up recently. without any error message.

### ISSUE THREAD

**Issue by mindgitrwx** [mmabrouk/chatgpt-wrapper#82]
<img width="480" alt="screenshot 2023-02-02 at 5 39 14 PM" src="https://user-images.githubusercontent.com/37054916/216273788-0067cd9f-9a4d-427f-9493-5bf959acd3ac.png">

Not for sure when does it happen first, but yesterday it worked well.

**Comment by ianholing** [comment]
Same here.. something have changed in the website, maybe because they are planning to release an official API :/

**Comment by claell** [comment]
Update the package. Solved it for me.

**Comment by jaybird110127** [comment]
Same thing here. My package is already up to date. Uninstalled and reinstalled, just in case. No change. I'm betting they've made some change to the API, and the script needs to be updated to account for it.

**Comment by claell** [comment]
Hm. Now I also get the problem again. But after I updated before, it worked for some time. But maybe that was unrelated.

**Comment by claell** [comment]
I saw that there is a small message box now on the site informing about high demand. Possibly, that needs to be closed first, as clicks in the window by the script might be blocked by that overlay. This is only speculation, though.

**Comment by Terex5505** [comment]
I also experienced this.
I think it had something to do with a ChatGPT change. This morning, on the ChatGPT website, I couldn't send a message with enter. I had to press the send button. However, that is no longer the case. It is working fine again.

**Comment by Terex5505** [comment]
> I also experienced this. I think it had something to do with a ChatGPT change. This morning, on the ChatGPT website, I couldn't send a message with enter. I had to press the send button. However, that is no longer the case. It is working fine again.

Never mind, i updated from 0.3.8 to 0.3.10, and I'm having the same issue again. But i dont think it is related to the wrapper update

**Comment by kurtmb** [comment]
I'm also running into this issue.  Has anyone solved it?

**Comment by Tecuya** [comment]
I just made a new version which changes the `model` parameter of the request back to what it was.  They changed it, so I changed the wrapper to match.  Now they changed it back to what it was, so I changed the wrapper back.   I was able to get it working on this newest version.  Please update and try again

**Comment by mindgitrwx** [comment]
It's work for me.

**Comment by jaybird110127** [comment]
Oh never mind, apparently they'd expired my session, and for some reason that's now exhibiting the same behavior as the bug seemingly squashed a few hours ago, rather than generating the typical "Unusable response…" message.

**Comment by Ale111** [comment]
Same here, seem OpenAI still not responding..

```
Solid:chatgpt_wrapper ale$ python chatgpt.py -l botlog.txt
Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> ?

Documented commands (type !help <topic>):
=========================================
!ask  !context  !exit  !file  !help  !log  !nav  !new  !read  !session  !stream

1> !session

```


and no more...

**Comment by jaybird110127** [comment]
In case this wasn't clear before: Apparently they can now expire your session in a way that does *not* result in the typical "Unusable response" error message. If this is the case, run "chatgpt install" and log in again, just like you did when you first installed it. Exit the shell, relaunch, and try your prompt again. Hope this helps.

**Comment by Giayychan** [comment]
> 

That worked for me

**Comment by mindgitrwx** [comment]
Error remains with recent version. 

```
"model": "text-davinci-002-render-next",
"model": "text-davinci-002-render",
```

Each one not properly have been worked recently.

**Comment by verazuo** [comment]
still meet this issue after reinstalling the package and relaunching `chatgpt install`.
Any other suggestions on how to fix it?

**Comment by tynguyen** [comment]
Check if your chatGPT account is a paid one instead of free. Follow the following issue to solve it.
https://github.com/mmabrouk/chatgpt-wrapper/issues/90

**Comment by mmabrouk** [comment]
This problem should have been fixed
