### ISSUE TITLE
unresponsive at prompt?

### ISSUE THREAD

**Issue by skytwosea** [mmabrouk/chatgpt-wrapper#84]
### Discussed in https://github.com/mmabrouk/chatgpt-wrapper/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **skytwosea** February  2, 2023</sup>
Successfully installed last night. This afternoon, I have gone through the steps to activate the shell environment, but no response is delivered when submitting a prompt.
1. activate my conda env & run `chatgpt install`
2. sign in, click through prompts in browser, reach browser prompt. Browser prompt works.
3. close browser window, !exit shell environment, restart shell env without `install` parameter. Program opens and sets a prompt: `1>`
.. but the prompt is unresponsive; nothing is returned when the prompt is submitted at `enter`.

I've restarted the shell, the conda environment, and my machine, and have updated the repo via `git pull origin main`, all to no avail; same problem, just completely unresponsive.

Any tips or suggestions? Any log files I can provide?
Kubuntu 5.15.0</div>

**Comment by mindgitrwx** [comment]
I think it is the same issue. https://github.com/mmabrouk/chatgpt-wrapper/issues/82

**Comment by mmabrouk** [comment]
Since this is the same issue, I will be closing this one
