### ISSUE TITLE
please log in to openai chat and accept the cookies box

### ISSUE THREAD

**Issue by lightningorb** [mmabrouk/chatgpt-wrapper#9]
```
~/dev/chatgpt-wrapper (main) $ chatGPT testing testing 123
Starting ... Please log in to OpenAI Chat and accept the cookies box
Press enter when you're done
```

not sure where the cookies box is.. so when i hit enter

```
Done
Asking...
Traceback (most recent call last):
  File "/usr/local/bin/chatGPT", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.1.0', 'console_scripts', 'chatgpt')())
  File "/Users/user/dev/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 119, in main
    print(Fore.GREEN + chatbot.ask(" ".join(sys.argv[1:])))
  File "/Users/user/dev/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 95, in ask
    self.__send_message(message)
  File "/Users/user/dev/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py", line 67, in __send_message
    box.click()
AttributeError: 'NoneType' object has no attribute 'click'
```

**Comment by pjahoorkar** [comment]
You have to first initiate using chatgpt install from the command line before calling the chatGPT function. This opens up a browser (assuming playwright is installed correctly) which will ask you to login and click some cookie, disclosure info that OpenAI needs before you can start using the chat. Once you are done with the disclosure boxes, you go back to the command line and click 'Enter' to see a 'You: ' prompt.

**Comment by MalteHB** [comment]
I experience the exact same issue.

**Comment by sander-wood** [comment]
Same here, I don't know where the cookies box is and have the same error "AttributeError: 'NoneType' object has no attribute 'click'". I have allowed all cookies, but didn't fix this issue.

**Comment by mmabrouk** [comment]
Please confirm whether you experience this issue also after running `chatgpt install`?

**Comment by shreyas301197** [comment]
i followed the chaptgpt install steps from cmd line, it does solve this issue but i still get timeout after i type in the very first prompt.

**Comment by MalteHB** [comment]
It works now - however, `readline` and `rich` needs to be manually installed. If on windows for `readline` use `pyreadline3`.

**Comment by mmabrouk** [comment]
Thanks @MalteHB . We are trying to solve the issue with readline, can you please help us with the PR (https://github.com/mmabrouk/chatgpt-wrapper/pull/14) as we don't have a windows machine to test.

**Comment by mmabrouk** [comment]
I am going to close this issue, since it seems the original issue can be solved by running install. I plan to add auto installation soon.
