### ISSUE TITLE
Does this work fro chatgpt plus?

### ISSUE THREAD

**Issue by avijay6** [mmabrouk/chatgpt-wrapper#90]

**Comment by mmabrouk** [comment]
Not sure, it would be nice if someone using the pro version can give feedback here

**Comment by avijay6** [comment]
I tried with Chatgpt plus and I  always get this message below:
Unusable response produced, maybe login session expired. Try 'pkill firefox' and 'chatgpt install'

**Comment by mindgitrwx** [comment]
Before using Chatgpt plus (previous chatgpt), Does it work?

**Comment by avijay6** [comment]
Yers, it was working before. Couple of days back, I started using chatgpt plus and wrapper is not working.

**Comment by avijay6** [comment]
I still works for chatgpt

**Comment by fanzhuyifan** [comment]
Change this line here
https://github.com/mmabrouk/chatgpt-wrapper/blob/f2d1101cb2f0e1b57fa9fef647a0eef04fea7e5c/chatgpt_wrapper/chatgpt.py#L131
Change "text-davinci-002-render" to "text-davinci-002-render-paid"

**Comment by guylozius** [comment]
@fanzhuyifan  how do access that file.

**Comment by avijay6** [comment]
> Change this line here
> 
> https://github.com/mmabrouk/chatgpt-wrapper/blob/f2d1101cb2f0e1b57fa9fef647a0eef04fea7e5c/chatgpt_wrapper/chatgpt.py#L131
> 
> 
> Change "text-davinci-002-render" to "text-davinci-002-render-paid"

Wow looks like its working!!!

**Comment by avijay6** [comment]
> @fanzhuyifan how do access that file.


Please find the chatgpt.py file in this directory

[chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper)/chatgpt_wrapper/

**Comment by luciano-fiandesio** [comment]
Just to confirm that changing the model to "text-davinci-002-render-paid" as specified by @avijay6 works!

**Comment by mmabrouk** [comment]
That is awesome to hear! It would be nice if someone with access to chatgpt plus could make this into a PR. Easiest way would be to add a command to toggle plus mode, best way would be to infer from the page's code whether we are in a plus mode.

**Comment by JerryGaoYJ** [comment]
> 我尝试使用 Chatgpt plus，但总是收到以下消息： 产生了无法使用的响应，可能登录会话已过期。尝试“pkill firefox”和“chatgpt install”

chatgpt plus 调用openai有优惠吗？

**Comment by fanzhuyifan** [comment]
> Change this line here
> 
> https://github.com/mmabrouk/chatgpt-wrapper/blob/f2d1101cb2f0e1b57fa9fef647a0eef04fea7e5c/chatgpt_wrapper/chatgpt.py#L131
> 
> Change "text-davinci-002-render" to "text-davinci-002-render-paid"

Fyi, the current "Default" model uses "text-davinci-002-render-sha", while the previous model that uses "text-davinci-002-render-paid" has been renamed "Legacy".

**Comment by mmabrouk** [comment]
I have updated the model used to text-davinci-002-render-sha (the turbo model) since it seems to be the default model now. Would anyone with a plus subscription check whether the code now works per default for them?

**Comment by Hoppsss** [comment]
> I have updated the model used to text-davinci-002-render-sha (the turbo model) since it seems to be the default model now. Would anyone with a plus subscription check whether the code now works per default for them?

Thank you this is working, as previous commentors mentioned changing it to 'text-davinci-002-render-paid' is also working for using the 'Legacy' model.

**Comment by nielstron** [comment]
For me it works with ChatGPT plus, I get "Unusable response produced, maybe login session expired. Try 'pkill firefox' and 'chatgpt install'" when I exceed the hourly limit
