### ISSUE TITLE
Can I skip the step of using the browser to obtain the session and use the wrapper by passing in the session to the wrapper?

### ISSUE THREAD

**Issue by iaston** [mmabrouk/chatgpt-wrapper#92]
In this way, sessions of multiple accounts can be saved in advance. When a session is unavailable or reaches the limit of 1 hour, it can be replaced with other sessions

**Comment by mmabrouk** [comment]
I am not sure I understand your proposal. Can you explain it more? Thanks!

**Comment by romn77** [comment]
+1 need help on that

**Comment by thehunmonkgroup** [comment]
Are you referring to an approach similar to this one? https://github.com/terry3041/pyChatGPT#obtaining-session_token

**Comment by thehunmonkgroup** [comment]
Browser backend is deprecated, no new features specific to the backend will be added.
